### PR TITLE
Fix `continual` hanging when canceled really fast

### LINKED ISSUE #793: `continual` hangs if canceled before `use` in its internal`bracket`
```scala
import cats.effect._
import cats.implicits._
import cats.effect.concurrent._
import java.{util => ju}

object Demo extends IOApp {

  def run(args: List[String]): IO[ExitCode] = {
    (IO(ju.UUID.randomUUID()), Deferred[IO, Unit]).tupled.flatMap {
      case (id, latch) =>
        val action: IO[Unit] = latch.complete(()) *> IO.never

        Concurrent.continual(action)(_ => IO.unit).start.flatMap(latch.get *> _.cancel) *>
          IO(println(s"foo $id"))
    }
  }.foreverM.as(ExitCode.Success)
}
```

This will run for a while, but eventually it'll print its final `foo` and never progress further.

I suppose this might be caused by a combination of `continual` being based on `start` and nested `start`s not getting cancelation propagated to them. But the most concerning part of it all is that it takes a couple hundred / couple thousand repeats to actually hang the program.

### PR DESCRIPTION
**Pull request by kubukoz**
Fixes #793

### CODE REVIEW

File: laws/shared/src/test/scala/cats/effect/ConcurrentContinualTests.scala [hunk 1]
```diff
@@ -20,8 +20,26 @@ import cats.effect.concurrent.Ref
...
+
+    val test = {
+      Deferred[IO, Unit]
+        .flatMap { started =>
+          (started.complete(()) *> IO.never: IO[Unit])
+            .continual(_ => IO.unit)
+            .start
+            .flatMap(started.get *> _.cancel)
+        }
+    }.replicateA(10000).as(true)
```
Comment (kubukoz) [inline laws/shared/src/test/scala/cats/effect/ConcurrentContinualTests.scala]: I haven't found a reliable way to reproduce the original issue without putting in arbitrary numbers. It can be anywhere from 1 to 7000... but the test runs very quickly and reliably hanged when the fix wasn't there.

**Comment by kubukoz** [comment]
The build failed due to `unsafeRunSync` being used on ScalaJS, but I wasn't able to reproduce the original issue on `testContext`. I'll split out the previously-hanging test into a new AsyncFunSpec.

**Comment by kubukoz** [comment]
Okay, get this - I moved from a 4-core machine to a 6-core one and the test hangs at ONE iteration 😂 😂

File: core/shared/src/main/scala/cats/effect/Concurrent.scala [hunk 2]
```diff
@@ -608,17 +608,20 @@ object Concurrent {
...
+          case ExitCase.Completed | ExitCase.Error(_) => fiber.join.attempt.flatMap(f).attempt.flatMap(r.complete)
+          case _                                      => F.unit //will be canceled in release of enclosing bracketCase
+        }
+      } {
+        case (fiber, ExitCase.Canceled) =>
+          // This cancel has to be here, and not in the `guaranteeCase` above, as the `use` of `bracketCase` might not be evaluated.
+          // See https://github.com/typelevel/cats-effect/issues/793
+          fiber.cancel *>
+            // We complete the promise because it's uncancelable - there needs to be *something* in it after this `bracketCase`.
+            r.complete(Left(new Exception("Continual fiber cancelled") with NoStackTrace))
```
Comment (SystemFw) [inline core/shared/src/main/scala/cats/effect/Concurrent.scala]: if this `bracketCase` is canceled, doesn't that mean that we never get to run `r.get` anyway?

Comment (kubukoz) [reply core/shared/src/main/scala/cats/effect/Concurrent.scala]: oh, it probably does, yeah. I'll test just to make sure.

Comment (kubukoz) [reply core/shared/src/main/scala/cats/effect/Concurrent.scala]: indeed, we never reach `*>` if it's canceled. Good catch!

**Comment by SystemFw** [comment]
I like this implementation better anyway (in addition to the bug fix :) ). Let me ponder on it just a bit more then I'll merge

**Comment by SystemFw** [comment]
I'm personally cool with merging now, should we wait for a second review?

**Comment by kubukoz** [comment]
I think it's okay to merge but would appreciate someone else looking at this with a fresh pair of eyes before releasing :)

File: core/shared/src/main/scala/cats/effect/Concurrent.scala [hunk 3]
```diff
@@ -605,20 +605,20 @@ object Concurrent {
...
+          case ExitCase.Completed | ExitCase.Error(_) => fiber.join.attempt.flatMap(f).attempt.flatMap(r.complete)
+          case _                                      => F.unit //will be canceled in release of enclosing bracketCase
+        }
+      } {
+        case (fiber, ExitCase.Canceled) =>
+          // This cancel has to be here, and not in the `guaranteeCase` above, as the `use` of `bracketCase` might not be evaluated.
+          // See https://github.com/typelevel/cats-effect/issues/793
+          fiber.cancel
+        case _ => F.unit
+      }.attempt *> r.get.rethrow
```
Comment (Avasil) [inline core/shared/src/main/scala/cats/effect/Concurrent.scala]: I feel like we could remove this `attempt` if we can make the following assumption for generic code:

AFAIK `F#start` can only fail with something like `RejectedExecutionException` before creating the fiber for cats IO and Monix Task. It returns `UIO` for ZIO and Monix BIO so `attempt` won't do anything there

Comment (kubukoz) [reply core/shared/src/main/scala/cats/effect/Concurrent.scala]: Removing this `attempt` causes this test to fail:

```scala

  testAsync("Concurrent.continual behaves like handleErrorWith on errors") { implicit ec =>
    implicit val cs: ContextShift[IO] = ec.ioContextShift

    val ex = new Exception("boom")
    val task = IO.raiseError[Unit](ex).continual(n => IO(n.swap.toOption.get))

    val f = task.unsafeToFuture()
    ec.tick()
    f.value shouldBe Some(Success(ex))
  }

```

I think it's because if `fiber` fails, `fiber.join.guaranteeCase` will also fail and we won't get the result from the Deferred (which would be a `Left[Throwable]`, so a valid `Either[Throwable, B]`), but a failed effect.

Comment (Avasil) [reply core/shared/src/main/scala/cats/effect/Concurrent.scala]: Ah, right, I've forgotten about `fa` 😅

**Comment by kubukoz** [comment]
Okay, let's merge :)
