### PR TITLE
Third optimization batch — map fusion

### LINKED ISSUE #92: IO.map should never be strictly evaluated
Currently `map` is defined like this:

```scala
  final def map[B](f: A => B): IO[B] =
    this match {
      case Pure(a) => try Pure(f(a)) catch { case NonFatal(e) => RaiseError(e) }
      case ref @ RaiseError(_) => ref
      case _ => flatMap(a => Pure(f(a)))
    }
```

Unfortunately this `map` operation is not equivalent with a `flatMap(f.andThen(pure))` because by not suspending execution it can trigger stack overflow errors.

As use-case, here's a toy `Iterant` implementation:

```scala
import cats.effect.IO

sealed trait Iterant[+A] {
  override def toString = "Iterant"
}

case class Next[+A](head: A, rest: IO[Iterant[A]]) extends Iterant[A]
case class Suspend[+A](rest: IO[Iterant[A]]) extends Iterant[A]
case class Halt(ex: Option[Throwable]) extends Iterant[Nothing]

// And a filter operation
def filter[A](f: A => Boolean)(stream: Iterant[A]): Iterant[A] =
  stream match {
    case Next(a, rest) => 
      val tail = rest.map(filter(f))
      if (f(a)) Next(a, tail) else Suspend(tail)
    case Suspend(rest) =>
      Suspend(rest.map(filter(f)))
    case Halt(_) => 
      stream
  }
```

The `filter` is pretty straightforward. Now lets build an already evaluated stream and filter it:

```scala
val stream = (0 until 1000000).foldLeft(Halt(None) : Iterant[Int]) { 
  (acc, elem) => Next(elem, IO.pure(acc)) 
}

filter((x: Int) => x % 2 == 0)(stream)
//=> StackOverflowException
```

Currently this `filter` operation blows with a `StackOverflowException`.

### Why this is bad

Having users to remember which operations are safe and which operations can blow up in their face and in what contexts makes for a really bad user experience. `io.map(f)` should be equivalent with `io.flatMap(x => pure(f(x)))` in all contexts, safety comes before performance.

Also `monix.tail.Iterant` is a real example shipping in Monix 3.0 which is generic over `F[_]` data types, making use of `cats.effect.Sync`.

So I'd like a test for this to be in `SyncLaws`.

### PR DESCRIPTION
**Pull request by alexandru**
Third PR addressing performance issues. Previous ones are #90 and #91.

Also addresses issue #92, but without the proposed laws.

---

In order to avoid stack-overflow errors, repeated `.map` calls trigger a `.flatMap` every 128 calls.

The rationale is thus — from my research the default stack size ranges from 320 KB on 32-bits operating systems to 1 MB on 64-bits operating systems. From my own tests a stack frame triggered by a `Function1` chaining consumes aproximately 32 bytes. So 128 fused `map` calls will consume `32 bytes * 128 = 4 KB` at a minimum (to which you add whatever else the user is doing on that stack).

In a real `flatMap` chain, which is what happens with `IO`, the performance does end up being dominated by `.flatMap` calls even with `.map` calls being mixed-in (a benchmark proving this will follow), however the improvements for `.map` are still good.

The important thing to watch out for in this optimization is that a degrading `.flatMap` isn't acceptable to make `.map` faster, but if we can manage a performance boost for fused `.map` calls without a `.flatMap` regression, then it's all good.

---

For benchmarking I've introduced 2 new benchmarks:

1. `MapCallsBenchmark` measures the performance of pure `map` calls (without being mixed within `.flatMap` loops)
2. `MapStreamBenchmark` measures the performance impact of a real-world use-case, showing what to expect from Monix's `Iterant` and possibly FS2

| Benchmark                          | 0.6-a581664 |       This PR |
|:-----------------------------------|------------:|--------------:|
| MapCallsBenchmark.batch120         |    5552.051 | **14680.810** |
| MapCallsBenchmark.batch30          |    4941.152 | **16196.342** |
| MapCallsBenchmark.one              |    6682.469 |      6167.908 |
| MapStreamBenchmark.batch120        |    2259.460 |      3176.587 |
| MapStreamBenchmark.batch30         |     918.054 |      1389.750 |
| MapStreamBenchmark.one             |    1418.865 |      1540.653 |

The other benchmarks:

| Benchmark                          | 0.6-a581664 |       This PR |
|:-----------------------------------|------------:|--------------:|
| AttemptBenchmark.errorRaised       |    1729.587 |      1750.409 |
| AttemptBenchmark.happyPath         |    2373.812 |      2316.602 |
| HandleErrorBenchmark.errorRaised   |    1974.071 |      2001.132 |
| HandleErrorBenchmark.happyPath     |    3005.539 |      2944.564 |
| DeepBindBenchmark.async            |     396.694 |       401.805 |
| DeepBindBenchmark.delay            |    6887.681 |      6601.429 |
| DeepBindBenchmark.pure             |    7849.842 |      7697.621 |
| ShallowBindBenchmark.async         |      90.336 |        83.502 |
| ShallowBindBenchmark.delay         |    5355.337 |      5324.081 |
| ShallowBindBenchmark.pure          |    6059.119 |      6239.963 |

Here I seem to have suffered a slight regression — not sure if this is a fluke or not, since the differences are very small, however if this is real, I need to investigate whether I can gain some extra throughput from somewhere else (win some, lose some).

### CODE REVIEW

**Comment by alexandru** [comment]
I might need to improve test coverage.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 1]
```diff
@@ -91,9 +91,14 @@ sealed abstract class IO[+A] {
    */
   final def map[B](f: A => B): IO[B] =
     this match {
-      case Pure(a) => try Pure(f(a)) catch { case NonFatal(e) => RaiseError(e) }
       case ref @ RaiseError(_) => ref
-      case _ => flatMap(a => Pure(f(a)))
+      case Map(source, g, index) =>
+        // Allowed to do 32 map operations in sequence before
+        // triggering `flatMap` in order to avoid stack overflows
+        if (index != 31) Map(source, g.andThen(f), index + 1)
```
Comment (daddykotex) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Quick question: out of curiosity, where does the 32 number comes from?

Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/IO.scala]: Right now it's a number pulled out of thin air (well, I've seen it used somewhere else) — the default stack size varies depending on platform, AFAIK ranging from 64Kb (Windows 32 bits) to 1 MB (on Linux 64 bits).

And we need a comfortable value to not blow people's stacks.

But now that you've mentioned it, I decided to do some testing and be thorough about it.

**Comment by alexandru** [comment]
I've got some refactoring ideas and some more testing to do, so placed this PR in the WIP state again.

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 1 above)
Comment (ritschwumm) [reply core/shared/src/main/scala/cats/effect/IO.scala]: sounds like it deserves a comment in the code telling the reader why this number has been chosen

**Comment by pakoito** [comment]
^^^ No Shame Sundays :D

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 1 above)
Comment (daddykotex) [reply core/shared/src/main/scala/cats/effect/IO.scala]: Thanks for the answer

**Comment by alexandru** [comment]
I've updated the description of the PR with the methodology for picking the right maximum number of fused `.map` calls.

**Comment by alexandru** [comment]
Update: added full benchmarking results and current interpretation.

File: core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala [hunk 2]
```diff
@@ -84,4 +84,34 @@ private[effect] object IOPlatform {
...
+   *
+   * <pre>
+   *   java -Dcats.effect.fusionMaxStackDepth=32 \
+   *        ...
+   * </pre>
+   */
+  private[effect] final val fusionMaxStackDepth =
+    Option(System.getProperty("cats.effect.fusionMaxStackDepth", ""))
+      .filter(s => s != null && s.nonEmpty)
+      .flatMap(s => Try(s.toInt).toOption)
```
Comment (rossabaker) [inline core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: We don't want to depend on a logger, but is it worth it to explain on stderr why we choked?

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 3]
```diff
@@ -93,9 +93,9 @@ sealed abstract class IO[+A] {
     this match {
       case ref @ RaiseError(_) => ref
       case Map(source, g, index) =>
-        // Allowed to do 32 map operations in sequence before
+        // Allowed to do 128 map operations in sequence before
```
Comment (rossabaker) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Comment is not true in Scala.js or sometimes in the presence of the sysprop.

Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/IO.scala]: Yes, I need to update the comment, thanks for pointing it out.

File: core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala (hunk 2 above)
Comment (alexandru) [reply core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: I'd prefer to not do it, since it introduces extra code — but I don't care much and if it's a popular demand, then OK.

What I'm thinking is that people won't modify this parameter unless they are in big trouble and we can have two issues:

1. given my calculations, the default value seems fine, but we might underestimate stack growth in common usage
2. we don't control all possible virtual machines, I have no idea for example what's the default stack size on Android or other non-Oracle JVMs

So increasing it won't increase performance unless used for very narrow use-cases and if people hit the stack limit because of this default, then we probably need to lower this limit in the library, with the overriding option being made available only to empower people to fix it without having to wait for another release.

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 3 above)
Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/IO.scala]: I changed that comment.

File: core/js/src/main/scala/cats/effect/internals/IOPlatform.scala [hunk 4]
```diff
@@ -44,4 +46,10 @@ private[effect] object IOPlatform {
       f(a)
     }
   }
+
+  /**
+   * Establishes the maximum stack depth for `IO#map` operations
+   * for JavaScript.
+   */
+  private[effect] final val fusionMaxStackDepth = 32
```
Comment (pakoito) [inline core/js/src/main/scala/cats/effect/internals/IOPlatform.scala]: Isn't the default supposed to be 128?

File: core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala [hunk 5]
```diff
@@ -84,4 +84,34 @@ private[effect] object IOPlatform {
...
+      .filter(_ > 0)
```
Comment (ChristopherDavenport) [inline core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: Just confirming what this looks like at `1` which is then reduced to `0` is that every operation is flatMapped rather than `Map`

Comment (alexandru) [reply core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: Yes, that's the intention — which made me realize that when that counter gets reset we should use a `Map(this, f, 0)` instead of a `FlatMap(this, f.andThen(pure))`.

File: core/js/src/main/scala/cats/effect/internals/IOPlatform.scala (hunk 4 above)
Comment (alexandru) [reply core/js/src/main/scala/cats/effect/internals/IOPlatform.scala]: That is the JavaScript version. I've updated the comment in `IO.scala` to not mention 128. Also this particular default is now changed to `31` since we are using inequality of the current index for the actual test as a very small performance optimization.

**Comment by alexandru** [comment]
The PR is ready for merging if you folks agree.

File: core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala (hunk 2 above)
Comment (rossabaker) [reply core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: Okay, I'll buy that.

**Comment by alexandru** [comment]
Any objections on merging this PR?
