### PR TITLE
Require Timer and shift automatically in concurrent IO operations

### LINKED ISSUE #229: Improve API for doing parallel execution
Manual `shift` model requires a user to keep in a head if the operation is async or not. Irrelevant of whether or not it's a good idea, API of `IO` fails short, requiring users to:

* Sprinkle cumbersome `timer.shift` calls
* Know where these are necessary

It would provide a much better user experience if we provide concurrent/parallel semantics out of the box, even with a perf hit of extra scheduling.

As a starting point, any of these changes would greatly improve using IO:

* Add these methods to IO:
```scala
// An infix version of doing manual shift. Less cumbersome to use for a pretty common operation
def shifted(implicit timer: Timer[IO]): IO[A] = timer.shift *> this

// A `start` that shifts automatically. Typically it's what people would want
def fork(implicit timer: Timer[IO]): IO[Fiber[IO, A]] = shifted.start
```

---

* Add suffixed variants to `race` operators creating async boundaries for users, e.g.:
```scala
def raceFork[A, B](fa: IO[A], fb: IO[B])(implicit timer: Timer[IO]): IO[Either[A, B]] =
  IO.race(fa.shifted, fb)
```
(Alternatively, we can change the base methods and Concurrent[IO] instance to do that for us. Concurrent[IO] instance will then require Timer[IO])

---

* Require `Timer[IO]` for `Parallel[IO]`. Do `timer.shift` ourselves in `parSequence` and `parTraverse`.

### PR DESCRIPTION
**Pull request by oleg-py**
Fixes #229.

### CODE REVIEW

File: core/shared/src/test/scala/cats/effect/internals/TestUtils.scala [hunk 1]
```diff
@@ -48,6 +52,35 @@ trait TestUtils {
...
+  private[this] val lock = new Semaphore(1)
+  def silenceSystemErrF[A](thunk: => Future[A])(implicit ec: ExecutionContext): Future[A] = {
+    lock.acquire()
+    // Silencing System.err
+    val oldErr = System.err
+    val outStream = new ByteArrayOutputStream()
+    val fakeErr = new PrintStream(outStream)
+    System.setErr(fakeErr)
+
+    Future.fromTry(Try(thunk)).flatten.andThen {
```
Comment (LukaJCB) [inline core/shared/src/test/scala/cats/effect/internals/TestUtils.scala]: Flatten isn't available on 2.11 unless you import cats syntax :)

Comment (oleg-py) [reply core/shared/src/test/scala/cats/effect/internals/TestUtils.scala]: Thanks, will fix when I get to code :)

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 2]
```diff
@@ -1171,8 +1176,8 @@ object IO extends IOInstances {
    * Also see [[racePair]] for a version that does not cancel
    * the loser automatically on successful results.
    */
-  def race[A, B](lh: IO[A], rh: IO[B]): IO[Either[A, B]] =
-    IORace.simple(lh, rh)
+  def race[A, B](lh: IO[A], rh: IO[B])(implicit timer: Timer[IO]): IO[Either[A, B]] =
+    IORace.simple(timer.shift *> lh, timer.shift *> rh)
```
Comment (johnynek) [inline core/shared/src/main/scala/cats/effect/IO.scala]: I wonder if we should just take timer, lh, and rh directly on simple and delay or even avoid the allocation of *>

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 3]
```diff
@@ -364,13 +365,9 @@ sealed abstract class IO[+A] extends internals.IOBinaryCompat[A] {
...
    * which creates a potential memory leak.
-   *
-   * IMPORTANT — this operation does not start with an asynchronous boundary.
-   * But you can use [[IO.shift(implicit* IO.shift]] to force an async
-   * boundary just before start.
    */
-  final def start: IO[Fiber[IO, A @uncheckedVariance]] =
-    IOStart(this)
+  final def start(implicit timer: Timer[IO]): IO[Fiber[IO, A @uncheckedVariance]] =
+    IOStart(timer.shift *> this)
```
Comment (johnynek) [inline core/shared/src/main/scala/cats/effect/IO.scala]: What if we just make `IOStart(timer, this)` so if we never actually evaluatue the result we save some allocations.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 4]
```diff
@@ -1202,8 +1207,8 @@ object IO extends IOInstances {
    * See [[race]] for a simpler version that cancels the loser
    * immediately.
    */
-  def racePair[A, B](lh: IO[A], rh: IO[B]): IO[Either[(A, Fiber[IO, B]), (Fiber[IO, A], B)]] =
-    IORace.pair(lh, rh)
+  def racePair[A, B](lh: IO[A], rh: IO[B])(implicit timer: Timer[IO]): IO[Either[(A, Fiber[IO, B]), (Fiber[IO, A], B)]] =
+    IORace.pair(timer.shift *> lh, timer.shift *> rh)
```
Comment (johnynek) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Similar comment about just taking the timer here vs manually shifting.

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 3 above)
Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/IO.scala]: 👍 agree with @johnynek

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 5]
```diff
@@ -674,17 +671,63 @@ private[effect] abstract class IOLowPriorityInstances extends IOParallelNewtype
   }
 
   implicit def ioSemigroup[A: Semigroup]: Semigroup[IO[A]] = new IOSemigroup[A]
+
+  implicit val ioEffect: Effect[IO] = new IOEffect
```
Comment (alexandru) [inline core/shared/src/main/scala/cats/effect/IO.scala]: The nice thing about this is that we get to keep the old `ioEffect`, with the previous type.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 6]
```diff
@@ -674,17 +671,63 @@ private[effect] abstract class IOLowPriorityInstances extends IOParallelNewtype
...
+
+  private[effect] class IOEffect extends Effect[IO] with StackSafeMonad[IO] {
```
Comment (alexandru) [inline core/shared/src/main/scala/cats/effect/IO.scala]: WTF I did not know there's a `StackSafeMonad` in Cats since Jun 20, 2017.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 7]
```diff
@@ -674,17 +671,63 @@ private[effect] abstract class IOLowPriorityInstances extends IOParallelNewtype
...
+    override def pure[A](a: A): IO[A] =
+      IO.pure(a)
+    override def unit: IO[Unit] =
+      IO.unit
+
+    override def map[A, B](fa: IO[A])(f: A => B): IO[B] =
```
Comment (alexandru) [inline core/shared/src/main/scala/cats/effect/IO.scala]: I would mark all of these defs as `final`.

Supposedly it helps the JVM optimize code. Never seen concrete evidence of it, but unless you want to leave the door open for overrides, there's no point in keeping them non-final.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 8]
```diff
@@ -674,17 +671,63 @@ private[effect] abstract class IOLowPriorityInstances extends IOParallelNewtype
...
 
-  implicit val parApplicative: Applicative[IO.Par] = new Applicative[IO.Par] {
+  implicit def parApplicative(implicit timer: Timer[IO]): Applicative[IO.Par] = new Applicative[IO.Par] {
     import IO.Par.{unwrap, apply => par}
 
     override def pure[A](x: A): IO.Par[A] =
       par(IO.pure(x))
     override def map2[A, B, Z](fa: IO.Par[A], fb: IO.Par[B])(f: (A, B) => Z): IO.Par[Z] =
-      par(IOParMap(unwrap(fa), unwrap(fb))(f))
+      par(IOParMap(timer.shift *> unwrap(fa), timer.shift *> unwrap(fb))(f))
```
Comment (alexandru) [inline core/shared/src/main/scala/cats/effect/IO.scala]: We might want to deploy the same trick I did in Monix for detecting already forked tasks.

But it doesn't have to happen in this PR, plus it probably needs good validation that it works in Monix first 🙂

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 6 above)
Comment (oleg-py) [reply core/shared/src/main/scala/cats/effect/IO.scala]: It's not that known because it's not appearing in user code, I think. But yeah, it's nice to not copy-paste same `tailRecM` across all your types :)

**Comment by oleg-py** [comment]
@alexandru there's a problem with MVar tests on JS with auto-shifting, can you take a look? 😄

File: core/shared/src/main/scala/cats/effect/internals/IOParMap.scala [hunk 9]
```diff
@@ -54,8 +56,8 @@ private[effect] object IOParMap {
           // NOTE: conn.pop() happens when cb gets called!
           conn.push(() => Cancelable.cancelAll(connA.cancel, connB.cancel))
 
-          IORunLoop.startCancelable(fa, connA, callbackA(connB))
-          IORunLoop.startCancelable(fb, connB, callbackB(connA))
+          IORunLoop.startCancelable(timer.shift *> fa, connA, callbackA(connB))
+          IORunLoop.startCancelable(timer.shift *> fb, connB, callbackB(connA))
```
Comment (johnynek) [inline core/shared/src/main/scala/cats/effect/internals/IOParMap.scala]: Do we need to shift both? Isn’t shifting just fa enough?

File: core/shared/src/main/scala/cats/effect/internals/IORace.scala [hunk 10]
```diff
@@ -65,15 +66,15 @@ private[effect] object IORace {
...
+      IORunLoop.startCancelable[A](timer.shift *> lh, connL, {
         case Right(a) =>
           onSuccess(active, connR, cb, Left(a))
         case Left(err) =>
           onError(active, cb, connR, err)
       })
 
       // Starts concurrent execution for the right value
-      IORunLoop.startCancelable[B](rh, connR, {
+      IORunLoop.startCancelable[B](timer.shift *> rh, connR, {
```
Comment (johnynek) [inline core/shared/src/main/scala/cats/effect/internals/IORace.scala]: Why isn’t shifting just the left side enough?

File: core/shared/src/test/scala/cats/effect/IOAppTests.scala [hunk 11]
```diff
@@ -17,33 +17,34 @@
...
 import org.scalatest.{AsyncFunSuite, BeforeAndAfterAll, Matchers}
-import scala.util.Success
 
 class IOAppTests extends AsyncFunSuite with Matchers with BeforeAndAfterAll with TestUtils {
   test("exits with specified code") {
     IOAppPlatform.mainFiber(Array.empty, Eval.now(implicitly))(_ => IO.pure(ExitCode(42)))
       .flatMap(_.join)
       .unsafeToFuture
-      .value shouldEqual (Some(Success(42)))
+      .map(_ shouldEqual 42)
```
Comment (johnynek) [inline core/shared/src/test/scala/cats/effect/IOAppTests.scala]: Shouldn’t this be an onComplete or something? If we get an exception will this be called?

Also, does the test framework just automatically handle Future? Why don’t we need to Await?

Comment (oleg-py) [reply core/shared/src/test/scala/cats/effect/IOAppTests.scala]: Test framework does. You return a `Future[Assertion]`, and this is what I'm creating with `map`. A failed `Future` gets reported as a failed test.

File: core/shared/src/main/scala/cats/effect/internals/IORace.scala (hunk 10 above)
Comment (oleg-py) [reply core/shared/src/main/scala/cats/effect/internals/IORace.scala]: It might be enough, but I'm not sure (my understanding of concurrency and internals is still a little bit off 😅 ), and I also didn't want to introduce a behavior (right-hand side start immediately on the current thread) which would break the symmetry between `IO.race(fa, fb)` and `IO.race(fb, fa).map(_.swap)`.

And if optimizing it away would not be a breaking change, so we can always do it later.

File: site/src/main/tut/datatypes/io.md [hunk 12]
```diff
@@ -1277,11 +1260,11 @@ There is also `cats.Traverse.sequence` which does this synchronously.
 
 ### parTraverse
 
-If you have a list of data and a way of turning each item into an IO, but you want a single IO for the results you can use `parTraverse` to run the steps in parallel. The IO tasks must be asynchronous, which if they are not you can use shift.
+If you have a list of data and a way of turning each item into an IO, but you want a single IO for the results you can use `parSequence` to run the steps in parallel.
```
Comment (gvolpe) [inline site/src/main/tut/datatypes/io.md]: `parTraverse`?

Comment (oleg-py) [reply site/src/main/tut/datatypes/io.md]: Thanks for noticing 👍

File: core/shared/src/main/scala/cats/effect/internals/IORace.scala (hunk 10 above)
Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/internals/IORace.scala]: I agree. Also if you fork one thread, then execute the other immediately, it's not really a fair race 🙂

I think that we'll also be able to do an optimization like I introduced in Monix, where we can detect tasks that are forked for the obvious cases. For example we can detect `shift *> delay(f)` and prevent an extra `shift`.

Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/internals/IORace.scala]: And for something like `race` it's more important to be fair than to be performant.

Comment (alexandru) [reply core/shared/src/main/scala/cats/effect/internals/IORace.scala]: ... such optimizations are dirty though, I wouldn't do it in this PR. I'd rather merge the PR ASAP, because @mpilquist needs it in FS2.
