### PR TITLE
Swap `System.exit` with `Runtime#halt`

### LINKED ISSUE #2586: `System.exit(1)` vs `Runtime#halt(1)` for fatal exceptions in `IOApp`
Continuing from:
- https://github.com/http4s/http4s/issues/5582#issuecomment-980693520.

### PR DESCRIPTION
**Pull request by alexandrustana**
This PR aims to fix #2586.

Even though these explanations
- https://github.com/http4s/http4s/issues/5582#issuecomment-978118101
- https://discordapp.com/channels/632277896739946517/632278585700384799/913131970702237696

mention that when encountering SOE it is safe to recover from it, they also state that it's not necessarily ideal to create a special case for handling it.

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala [hunk 1]
```diff
@@ -57,7 +57,7 @@ private[internals] object PoolUtils {
             case t: Throwable =>
               // under most circumstances, this will work even with fatal errors
               t.printStackTrace()
-              System.exit(1)
+              Runtime.getRuntime().halt(1)
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala:60]: Should we check if `t` is a fatal exception before deciding what to do?

Comment (alexandrustana) [reply core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala:60]: It is checked above that it is `NonFatal`, so I'm guessing we will only get fatal exceptions at this point.

Comment (armanbilge) [reply core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala:60]: Aha, so it is! Apologies for the tunnel vision 😅

Comment (alexandrustana) [reply core/jvm/src/main/scala/cats/effect/internals/PoolUtils.scala:60]: No worries, thank you for checking the PR 🙂

**Review by armanbilge — APPROVED** [review]

**Review by djspiewak — APPROVED** [review]
