### PR TITLE
Parallel performance improvement

### LINKED ISSUE #2095: [CE3] Kleisli Stack safety
This code is Ok with CE2, but fail with `StackOverflowError` in CE3.
```scala
import cats.effect.{ExitCode, IO, IOApp}
import cats.syntax.all._
import cats.data.Kleisli

object MainKleisli extends IOApp {

  override def run(args: List[String]): IO[ExitCode] = {
    val N = 10000
    var i = 0

    List.fill(N)(0).traverse_(_ => Kleisli.liftF(IO(i += 1))).run("Go...") *>
      IO(println(s"i: ${i}")) *>
      IO(assert(i === N, s"i: $i != $N")).as(ExitCode.Success)
  }
}
```

### LINKED ISSUE #2155: Improve performance of Parallel by overriding map2 to avoid tupling
This is a bit of low-hanging fruit, but we currently define `Parallel[F]` given `GenSpawn[F, _]` in terms of the following construction:

```scala
      final override def map2[A, B, Z](fa: ParallelF[F, A], fb: ParallelF[F, B])(
          f: (A, B) => Z): ParallelF[F, Z] =
        ParallelF(
          F.both(ParallelF.value(fa), ParallelF.value(fb)).map { case (a, b) => f(a, b) }
        )
```

That's cool but there's a lot of unnecessary boxing in here, both in `both` and in `racePair` underneath. We can actually do a lot better given `GenConcurrent[F, _]`, which will be the case quite a lot of the time in practical code. However, rather than creating some sort of sneaky implicit prioritization thing, I think the right approach here is probably to add a `mapBoth` function (feel free to bikeshed the name) to `GenSpawn`, then override it in `GenConcurrent` with a more efficient implementation in terms of `Fiber` and `Deferred`.

Overall this probably sounds a lot more intimidating of an enhancement than it actually is. Tldr, add the following to `GenSpawn`:

```scala
def mapBoth[A, B, C](fa: F[A], fb: F[B])(f: (A, B) => F[C]): F[C] = ???
```

Delegate the implementation to `both` in `GenSpawn`, but then override that implementation in `GenConcurrent` with something implemented in terms of `Fiber` and `Deferred`. The results should be a noticeable improvement in performance of the `par` operators.

### PR DESCRIPTION
**Pull request by manufacturist**
First PR. Be gentle 🙏 🎉  PR covering #2155:
- [x] ~mapBoth~
- [x] ~map2 in terms of mapBoth~
- [x] ~GenConcurrent.mapBoth override~
- [x] `map2` & `map2Eval` overrides (with `mapBoth` solution)
- [x] ~unit tests~ (No longer needed due to overriding `map2` & `map2Eval`)
- [x] benchmarks + profiling results

> Delegate the implementation to both in GenSpawn, but then override that implementation in GenConcurrent with something implemented in terms of Fiber and Deferred. The results should be a noticeable improvement in performance of the par operators.

In abstract, I need to ensure that two effects run in parallel, obtain their results and map over them.

Qs:
1. The `cancelled *> never` trick ensures that `never` will never run, therefore it is only used throughout the cats-effect code to help with matching the type signature where needed. Is this correct?
2. When joining a fiber in a construct such as `outcome <- poll(workFiber.join)`, is there any need for calling `onCancel` or `guarantee`? Is there the possibility of having the main fiber cancelled while the `workFiber` hasn't joined yet?  And if yes, then the mentioned constructs guards us against such scenarios?
3. Why would the solution need to be implemented in terms of fibers AND `Deferred`? Why isn't fibers enough, e.g.
```scala
  override def mapBoth[A, B, C](fa: F[A], fb: F[B])(f: (A, B) => F[C]): F[C] = {
    implicit val F: GenConcurrent[F, E] = this

    uncancelable { poll =>
      for {
        fiberA <- start(fa)
        fiberB <- start(fb)

        outcomeA <- poll(fiberA.join).guarantee(fiberA.cancel)
        outcomeB <- poll(fiberB.join).guarantee(fiberB.cancel)

        resultC <- (outcomeA, outcomeB) match {
          case (Outcome.Succeeded(fa), Outcome.Succeeded(fb)) =>
            fa.product(fb).flatMap { case (a, b) => f(a, b) }

          case (Outcome.Errored(e), _) => raiseError(e)
          case (_, Outcome.Errored(e)) => raiseError(e)
          case (Outcome.Canceled(), _) => F.canceled *> never
          case (_, Outcome.Canceled()) => F.canceled *> never
        }
      } yield resultC
     }
    }
```

### CODE REVIEW

File: kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala [hunk 1]
```diff
@@ -523,6 +526,13 @@ object GenSpawn {
     override def both[A, B](fa: OptionT[F, A], fb: OptionT[F, B]): OptionT[F, (A, B)] =
       OptionT(F.both(fa.value, fb.value).map(_.tupled))
 
+    override def mapBoth[A, B, C](fa: OptionT[F, A], fb: OptionT[F, B])(
```
Comment (djspiewak) [inline kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala]: I actually don't think we need to override `mapBoth` for the transformers! Which is nice because all these overrides are annoying.

File: kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala [hunk 2]
```diff
@@ -125,6 +125,36 @@ trait GenConcurrent[F[_], E] extends GenSpawn[F, E] {
...
+
+        _ <- poll(fiberA.join)
+        _ <- poll(fiberB.join)
+
+        outcomeA <- poll(resultA.get)
+        outcomeB <- poll(resultB.get)
+
+        resultC <- (outcomeA, outcomeB) match {
+          case (Outcome.Succeeded(fa), Outcome.Succeeded(fb)) =>
+            fa.product(fb).flatMap { case (a, b) => f(a, b) }
```
Comment (djspiewak) [inline kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala]: We can avoid the tuple allocation here by using `fa.flatMap(a => fb.flatMap(b => f(a, b)))` rather than using `product`.

**Review by djspiewak — COMMENTED** [review]
This is great! Just a couple adjustments. Also, @vasilmkd do we have a `parTraverse` benchmark already? We should add one and check the difference.

File: kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala (hunk 1 above)
Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/GenSpawn.scala]: Is this tested in the laws? If so, let's drop it.

**Comment by vasilmkd** [comment]
Unfortunately I don't think we have a `parTraverse` benchmark. It would be great to have a suite of benchmarks for `traverse` and `parTraverse`, maybe it can be done in a sepate PR so that we can test before and after. Sorry about this.

**Comment by djspiewak** [comment]
> Unfortunately I don't think we have a parTraverse benchmark. It would be great to have a suite of benchmarks for traverse and parTraverse, maybe it can be done in a sepate PR so that we can test before and after. Sorry about this.

No worries! I was thinking of just doing it as part of this PR actually. @manufacturist are you comfortable working with JMH? Would you like to give it a try? Otherwise I (or Vasil) can get to it and push here.

**Comment by vasilmkd** [comment]
Feel free to ask and to look into the `benchmarks` sources and copy/paste liberally.

**Comment by djspiewak** [comment]
Missed the questions! Answers incoming…

> The `cancelled *> never` trick ensures that never will never run, therefore it is only used throughout the cats-effect code to help with matching the type signature where needed. Is this correct?

The problem here is a little more existential. If it was just a bit of type juggling I would be a lot more worried about it! Here's the issue:

```scala
F.uncancelable(_ => F.both(F.canceled.as(42), F.unit))
```

What should this produce?

The problem here is the type signature of `both` is too limited to properly represent this scenario. We can't produce a value of type `(Int, Unit)`, and we can't cancel ourselves (because of `uncancelable`), so we have to either error or spin forever. The error approach doesn't work either though because it might be caught within the `uncancelable` block, etc etc.

> When joining a fiber in a construct such as outcome <- poll(workFiber.join), is there any need for calling onCancel or guarantee? Is there the possibility of having the main fiber cancelled while the workFiber hasn't joined yet? And if yes, then the mentioned constructs guards us against such scenarios?

Precisely as you said. :-) Also I'm realizing that there's actually a leak here: it's possible that the parent fiber is canceled prior to the first `poll`, in which case it will show up there but only one of the child fibers will be canceled! We need something a little trickier using `guaranteeCase` to ensure that *both* fibers get canceled if either of them error or cancel.

> Why would the solution need to be implemented in terms of fibers AND Deferred? Why isn't fibers enough, e.g.

I believe you're correct! I'm pretty sure we don't need `Deferred` at all here.

**Comment by manufacturist** [comment]
> > Unfortunately I don't think we have a parTraverse benchmark. It would be great to have a suite of benchmarks for traverse and parTraverse, maybe it can be done in a sepate PR so that we can test before and after. Sorry about this.
> 
> No worries! I was thinking of just doing it as part of this PR actually. @manufacturist are you comfortable working with JMH? Would you like to give it a try? Otherwise I (or Vasil) can get to it and push here.

I'll give it a try 😄

**Comment by djspiewak** [comment]
@manufacturist If it helps, I literally always copy/paste from something pre-existing for JMH. I recommend just copying something like the `BothBenchmark`, removing all the cases, and writing a new one for `parTraverse`. Call it `ParallelBenchmark` or something like that. The `parTraverse` benchmark can probably be pretty simple, just like traverse over a list of size `n` (where `n: Int` is a `@Param` and you can set it to like, `"10000"` or something). Anyway, just create a list of size `n` and then `parTraverse` over it to an `IO` which uses `BlackHole.consumeCPU()` with some small (but not totally trivial number). It might be useful to also add an identical `traverse` benchmark in the same file. We would expect that `parTraverse` would be *k* times faster than `n`, where *k* is the number of physical threads on the underlying machine.

**Comment by vasilmkd** [comment]
Maintainers caught admitting copy/pasting code all over the place.

**Comment by djspiewak** [comment]
> Maintainers caught admitting copy/pasting code all over the place.

My favorite Sublime key combo is Cmd-Shift-D: it duplicates the current line. :-P

**Comment by manufacturist** [comment]
Updated the `mapBoth` override to drop `Deffered` from the solution & removed overrides for `mapBoth` in instances. Added the benchmarks for `parTraverse` and `traverse` only with `val cpuTimeTokens = 10000`.

### Executing Machine

```
Processor Name:         Quad-Core Intel Core i7
Processor Speed:        2,2 GHz
Number of Processors:   1
Total Number of Cores:  4
```

All benchmarks executed with variations of `jmh:run -i X -wi Y -f 2 -t 4 cats.effect.benchmarks.ParallelBenchmark`

### CPU Time Tokens = 200

```
[info] Benchmark                                  (size)   Mode  Cnt      Score     Error  Units
[info] ParallelBenchmark.traverse100               10000  thrpt   15  37910.533 ± 398.023  ops/s
[info] ParallelBenchmark.traverse1000              10000  thrpt   15   4742.708 ± 207.744  ops/s
[info] ParallelBenchmark.traverse10000             10000  thrpt   15    506.790 ±  25.914  ops/s
[info] ParallelBenchmark.parTraverseBoth100        10000  thrpt   15   3632.091 ± 354.683  ops/s
[info] ParallelBenchmark.parTraverseBoth1000       10000  thrpt   15    435.991 ±   8.477  ops/s
[info] ParallelBenchmark.parTraverseBoth10000.     10000  thrpt   15     55.030 ±   0.788  ops/s
[info] ParallelBenchmark.parTraverseMapBoth100     10000  thrpt   10   7824.942 ± 111.829  ops/s
[info] ParallelBenchmark.parTraverseMapBoth1000    10000  thrpt   10   1049.031 ± 151.450  ops/s
[info] ParallelBenchmark.parTraverseMapBoth10000   10000  thrpt   10    108.418 ±  13.729  ops/s
```

### CPU Time Tokens = 2000 - `mapBoth` approach

```
[info] Benchmark                           (size)   Mode  Cnt     Score     Error  Units
[info] ParallelBenchmark.parTraverse100     10000  thrpt    5  7291.586 ± 621.810  ops/s
[info] ParallelBenchmark.parTraverse1000    10000  thrpt    5   729.836 ± 143.587  ops/s
[info] ParallelBenchmark.parTraverse10000   10000  thrpt    5    62.743 ±   3.068  ops/s
[info] ParallelBenchmark.traverse100        10000  thrpt    5  6977.727 ± 218.018  ops/s
[info] ParallelBenchmark.traverse1000       10000  thrpt    5   755.024 ±  26.890  ops/s
[info] ParallelBenchmark.traverse10000      10000  thrpt    5    72.412 ±  10.234  ops/s
```

### CPU Time Tokens = 5000 - `mapBoth` approach

```
[info] ParallelBenchmark.parTraverse100     10000  thrpt    6  4741.184 ± 173.918  ops/s
[info] ParallelBenchmark.parTraverse1000    10000  thrpt    6   476.457 ±  74.728  ops/s
[info] ParallelBenchmark.parTraverse10000   10000  thrpt    6    38.966 ±   2.960  ops/s
[info] ParallelBenchmark.traverse100        10000  thrpt    6  2945.512 ±  55.656  ops/s
[info] ParallelBenchmark.traverse1000       10000  thrpt    6   298.424 ±  25.320  ops/s
[info] ParallelBenchmark.traverse10000      10000  thrpt    6    31.545 ±   0.906  ops/s
```

### CPU Time Tokens = 10000 - `mapBoth` approach

```
[info] ParallelBenchmark.parTraverse100     10000  thrpt    6  2726.039 ±  19.494  ops/s
[info] ParallelBenchmark.parTraverse1000    10000  thrpt    6   283.107 ±   2.026  ops/s
[info] ParallelBenchmark.parTraverse10000   10000  thrpt    6    25.774 ±   4.185  ops/s
[info] ParallelBenchmark.traverse100        10000  thrpt    6  1496.449 ± 147.759  ops/s
[info] ParallelBenchmark.traverse1000       10000  thrpt    6   151.205 ±   3.623  ops/s
[info] ParallelBenchmark.traverse10000      10000  thrpt    6    15.209 ±   1.546  ops/s
```

<hr>

How I interpret the benchmarks:
* Non-CPU intensive tasks result in bad `parTraverse` performance due to an occuring `performance cost` from internal CE operating mechanisms (it's a black box for me 😅)
* CPU intensive tasks are an excellent candidate for `parTraverse`
* The `mapBoth` solution provides a better performance than the old one using `both` (`GenConcurrent.mapBoth` not overriden)

File: benchmarks/src/main/scala/cats/effect/benchmarks/ParallelBenchmark.scala [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+
+import org.openjdk.jmh.annotations._
+import org.openjdk.jmh.infra.Blackhole
+
+import java.util.concurrent.TimeUnit
+
+/**
+ * To do comparative benchmarks between versions:
+ *
+ *     benchmarks/run-benchmark BothBenchmark
```
Comment (vasilmkd) [inline benchmarks/src/main/scala/cats/effect/benchmarks/ParallelBenchmark.scala]: Please replace all occurrences of `BothBenchmark` with `ParallelBenchmark`.

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 4]
```diff
@@ -53,7 +53,7 @@ trait GenSpawnInstances {
       final override def map2[A, B, Z](fa: ParallelF[F, A], fb: ParallelF[F, B])(
           f: (A, B) => Z): ParallelF[F, Z] =
         ParallelF(
-          F.both(ParallelF.value(fa), ParallelF.value(fb)).map { case (a, b) => f(a, b) }
+          F.mapBoth(ParallelF.value(fa), ParallelF.value(fb)) { case (a, b) => F.pure(f(a, b)) }
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: I think the `case` is now unnecessary and can be dropped.

File: kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala [hunk 5]
```diff
@@ -125,6 +125,30 @@ trait GenConcurrent[F[_], E] extends GenSpawn[F, E] {
...
+            fa.flatMap(a => fb.flatMap(b => f(a, b)))
+
+          case (Outcome.Errored(e), _) => raiseError(e)
+          case (_, Outcome.Errored(e)) => raiseError(e)
+          case (Outcome.Canceled(), _) => F.canceled *> never
+          case (_, Outcome.Canceled()) => F.canceled *> never
+        }
+      } yield resultC
+    }
+  }
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala]: Now that there are no `GenConcurrent` constructs used, we should try to move this code in `GenSpawn`. This was an observation by @TimWSpence, thank you!

Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala]: I feel this block of code needs a good review from more pairs of eyes.

**Review by vasilmkd — CHANGES_REQUESTED** [review]

File: kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala (hunk 5 above)
Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala]: That being said, if the logic does end up changing, this code may indeed need to live in `GenConcurrent`.

**Comment by vasilmkd** [comment]
@manufacturist Are the benchmark results you posted only for the current branch which includes the changes in this PR?

**Comment by manufacturist** [comment]
> @manufacturist Are the benchmark results you posted only for the current branch which includes the changes in this PR?

They are. The first batch (`CPU Time Tokens = 200`) also includes results for the old implementation of `map2`.

**Comment by vasilmkd** [comment]
I would like to split the benchmark code out of this PR, open it as a separate PR and then when we merge it, rebase this PR and do a proper comparison for every case between `series/3.x` and this branch.

**Comment by vasilmkd** [comment]
@manufacturist The original issue has been changed in light of new information. I suggest that we split out the benchmarks into a separate PR and push that through, and then we can work together on tackling this problem again and be a bit more focused this time round.

**Comment by djspiewak** [comment]
I think it's okay to keep updating this PR in light of the revised requirements. It's good history. :-) Agree that splitting the benchmarks out into a separate PR (#2167) is a good move.

**Comment by vasilmkd** [comment]
Can you drop the commit that adds the `ParallelBenchmark`?

**Comment by manufacturist** [comment]
> Can you drop the commit that adds the `ParallelBenchmark`?

Will do so in ~12 hours.

**Comment by djspiewak** [comment]
@manufacturist New plan! Let's skip the `mapBoth` in `GenSpawn` and instead just put that same implementation into `map2` for `commutativeApplicativeForParallelF`. In fact, if you copy/paste the implementation into `map2Eval` in the same class, it should *also* fix #2095. This is great. :-D

@vasilmkd gets all the credit for this realization btw.

**Comment by vasilmkd** [comment]
Plan of attack that @manufacturist can follow tomorrow:

- [ ] Drop the `ParallelBenchmark` commit and rebase on `series/3.x`, you'll get it from there.
- [ ] Reimplement `map2` in `commutativeApplicativeForParallelF`.
- [ ] You can attempt to override `map2Eval` in `commutativeApplicativeForParallelF` too, and then I will push the unit tests that we have prepared for that particular bug, or you can choose to ignore this, your call, we can also add that code to the already open PR

**Comment by manufacturist** [comment]
Will rerun the benchmarks later today to be able to compare them with the ones from #2167.

**Comment by manufacturist** [comment]
Finished running the benchmarks. They can be compared with the ones from the [other PR](https://github.com/typelevel/cats-effect/pull/2167#issuecomment-888030397):  

```sbt
[info] Benchmark                      (cpuTokens)  (size)   Mode  Cnt      Score     Error  Units
[info] ParallelBenchmark.parTraverse          100     100  thrpt   20   9944.533 ± 211.074  ops/s
[info] ParallelBenchmark.parTraverse          100    1000  thrpt   20   1428.851 ±   9.781  ops/s
[info] ParallelBenchmark.parTraverse          100   10000  thrpt   20    139.946 ±   1.383  ops/s
[info] ParallelBenchmark.parTraverse         1000     100  thrpt   20   8184.030 ±  39.369  ops/s
[info] ParallelBenchmark.parTraverse         1000    1000  thrpt   20   1008.832 ±   2.568  ops/s
[info] ParallelBenchmark.parTraverse         1000   10000  thrpt   20     98.693 ±   0.729  ops/s
[info] ParallelBenchmark.parTraverse        10000     100  thrpt   20   2526.056 ±  29.223  ops/s
[info] ParallelBenchmark.parTraverse        10000    1000  thrpt   20    257.168 ±   2.535  ops/s
[info] ParallelBenchmark.parTraverse        10000   10000  thrpt   20     25.164 ±   0.491  ops/s
[info] ParallelBenchmark.parTraverse       100000     100  thrpt   20    305.078 ±   1.061  ops/s
[info] ParallelBenchmark.parTraverse       100000    1000  thrpt   20     30.497 ±   0.589  ops/s
[info] ParallelBenchmark.parTraverse       100000   10000  thrpt   20      3.006 ±   0.084  ops/s
[info] ParallelBenchmark.parTraverse      1000000     100  thrpt   20     31.570 ±   0.133  ops/s
[info] ParallelBenchmark.parTraverse      1000000    1000  thrpt   20      3.164 ±   0.017  ops/s
[info] ParallelBenchmark.parTraverse      1000000   10000  thrpt   20      0.330 ±   0.034  ops/s
[info] ParallelBenchmark.traverse             100     100  thrpt   20  61728.601 ± 694.063  ops/s
[info] ParallelBenchmark.traverse             100    1000  thrpt   20   7589.424 ±  84.756  ops/s
[info] ParallelBenchmark.traverse             100   10000  thrpt   20    873.365 ±   2.606  ops/s
[info] ParallelBenchmark.traverse            1000     100  thrpt   20  15077.902 ±  89.639  ops/s
[info] ParallelBenchmark.traverse            1000    1000  thrpt   20   1622.568 ±  10.988  ops/s
[info] ParallelBenchmark.traverse            1000   10000  thrpt   20    165.695 ±   1.015  ops/s
[info] ParallelBenchmark.traverse           10000     100  thrpt   20   1770.700 ±   0.867  ops/s
[info] ParallelBenchmark.traverse           10000    1000  thrpt   20    177.990 ±   0.240  ops/s
[info] ParallelBenchmark.traverse           10000   10000  thrpt   20     17.709 ±   0.125  ops/s
[info] ParallelBenchmark.traverse          100000     100  thrpt   20    179.605 ±   0.153  ops/s
[info] ParallelBenchmark.traverse          100000    1000  thrpt   20     17.886 ±   0.097  ops/s
[info] ParallelBenchmark.traverse          100000   10000  thrpt   20      1.737 ±   0.067  ops/s
[info] ParallelBenchmark.traverse         1000000     100  thrpt   20     17.896 ±   0.069  ops/s
[info] ParallelBenchmark.traverse         1000000    1000  thrpt   20      1.729 ±   0.075  ops/s
[info] ParallelBenchmark.traverse         1000000   10000  thrpt   20      0.176 ±   0.008  ops/s
```

The `traverse` ones (`cpuTokens = 100`) are slightly worse possibly due to the fact that I ran the benchmarks immediately after a work day, whereas for the other ones I restarted my machine beforehand (The other run took 4h, this one took 4h20m).

For my machine, the performance gain for `parTraverse` is visible up until the `10k cpuTokens / 10k size` benchmark. Afterwards it kinda syncs with the other batch of results. I would've been happy (and curious) to provide some benchmarks with 8 threads, however my machine is limited in this situation 🤷

**Comment by vasilmkd** [comment]
Here are the runs from a 16 core cloud instance:

`series/3.x`:
```
Benchmark                      (cpuTokens)  (size)   Mode  Cnt     Score    Error  Units
ParallelBenchmark.parTraverse          100     100  thrpt   10  1022.928 ± 97.351  ops/s
ParallelBenchmark.parTraverse          100    1000  thrpt   10   590.857 ± 17.301  ops/s
ParallelBenchmark.parTraverse          100   10000  thrpt   10   114.312 ±  1.927  ops/s
ParallelBenchmark.parTraverse         1000     100  thrpt   10   920.307 ± 61.221  ops/s
ParallelBenchmark.parTraverse         1000    1000  thrpt   10   541.315 ±  8.762  ops/s
ParallelBenchmark.parTraverse         1000   10000  thrpt   10    91.450 ±  9.160  ops/s
ParallelBenchmark.parTraverse        10000     100  thrpt   10   627.563 ± 11.182  ops/s
ParallelBenchmark.parTraverse        10000    1000  thrpt   10   282.210 ±  4.189  ops/s
ParallelBenchmark.parTraverse        10000   10000  thrpt   10    36.335 ±  0.490  ops/s
ParallelBenchmark.parTraverse       100000     100  thrpt   10   364.892 ±  5.622  ops/s
ParallelBenchmark.parTraverse       100000    1000  thrpt   10    47.056 ±  0.736  ops/s
ParallelBenchmark.parTraverse       100000   10000  thrpt   10     4.995 ±  0.053  ops/s
ParallelBenchmark.parTraverse      1000000     100  thrpt   10    46.086 ±  0.445  ops/s
ParallelBenchmark.parTraverse      1000000    1000  thrpt   10     5.107 ±  0.044  ops/s
ParallelBenchmark.parTraverse      1000000   10000  thrpt   10     0.524 ±  0.005  ops/s
```

`This PR`:
```
Benchmark                      (cpuTokens)  (size)   Mode  Cnt     Score    Error  Units
ParallelBenchmark.parTraverse          100     100  thrpt   10  1923.358 ± 94.031  ops/s
ParallelBenchmark.parTraverse          100    1000  thrpt   10   802.741 ± 20.411  ops/s
ParallelBenchmark.parTraverse          100   10000  thrpt   10   213.009 ±  5.766  ops/s
ParallelBenchmark.parTraverse         1000     100  thrpt   10  1452.882 ± 55.123  ops/s
ParallelBenchmark.parTraverse         1000    1000  thrpt   10   735.565 ± 22.182  ops/s
ParallelBenchmark.parTraverse         1000   10000  thrpt   10   156.585 ±  5.453  ops/s
ParallelBenchmark.parTraverse        10000     100  thrpt   10   976.165 ± 59.770  ops/s
ParallelBenchmark.parTraverse        10000    1000  thrpt   10   316.931 ± 31.421  ops/s
ParallelBenchmark.parTraverse        10000   10000  thrpt   10    41.550 ±  2.564  ops/s
ParallelBenchmark.parTraverse       100000     100  thrpt   10   396.673 ±  6.149  ops/s
ParallelBenchmark.parTraverse       100000    1000  thrpt   10    48.691 ±  0.602  ops/s
ParallelBenchmark.parTraverse       100000   10000  thrpt   10     5.116 ±  0.065  ops/s
ParallelBenchmark.parTraverse      1000000     100  thrpt   10    46.660 ±  0.361  ops/s
ParallelBenchmark.parTraverse      1000000    1000  thrpt   10     5.093 ±  0.089  ops/s
ParallelBenchmark.parTraverse      1000000   10000  thrpt   10     0.528 ±  0.004  ops/s
```

I think this is a spectacular improvement and well worth the code duplication. Amazing work @manufacturist! You should be proud.

**Comment by vasilmkd** [comment]
I will do another pass over the code and give my final approval later.

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 6]
```diff
@@ -53,7 +53,49 @@ trait GenSpawnInstances {
       final override def map2[A, B, Z](fa: ParallelF[F, A], fb: ParallelF[F, B])(
           f: (A, B) => Z): ParallelF[F, Z] =
         ParallelF(
-          F.both(ParallelF.value(fa), ParallelF.value(fb)).map { case (a, b) => f(a, b) }
+          F.uncancelable { poll =>
+            for {
+              fiberA <- F.start(ParallelF.value(fa))
+              fiberB <- F.start(ParallelF.value(fb))
+
+              a <- F.onCancel(poll(fiberA.join), fiberB.cancel).flatMap[A] {
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: Here's a scenario, we get canceled while trying to `join` the `fiberA`. However, this does not cancel `fiberA`.

Is this a valid concern or am I missing something?

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 7]
```diff
@@ -53,7 +53,49 @@ trait GenSpawnInstances {
...
+                case Outcome.Succeeded(fa) => fa
+                case Outcome.Errored(e) => fiberB.cancel *> F.raiseError(e)
+                case Outcome.Canceled() => fiberB.cancel *> F.never
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: I don't quite understand this interaction. I fear this will enter `F.never` here.

Should this line be: `fiberB.cancel *> F.canceled *> F.never` instead? I also don't quite understand how this all interacts with the outer `uncancelable`.

**Review by vasilmkd — COMMENTED** [review]
@djspiewak Please take a close look when reviewing the changes. I'd love an explanation on a couple of confusion points I encountered in the review. Thanks.

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala (hunk 7 above)
Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: This should indeed be `poll(fiberB.cancel *> F.canceled *> F.never)` (and analogously in the `b` case)

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala (hunk 6 above)
Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: This is a valid concern! We need to cancel *both* of the fibers if either `join` is canceled. And in fact, we need to ensure that this cancelation is itself run in parallel, so the correct finalizer here would be `F.onCancel(poll(fiberA.join), F.both(fiberB.cancel, fiberA.cancel))`.

**Review by djspiewak — CHANGES_REQUESTED** [review]
Just the changes noted and confirmed in @vasilmkd's review. Otherwise, this looks good! Very impressive work.

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 8]
```diff
@@ -53,7 +53,53 @@ trait GenSpawnInstances {
...
+            for {
+              fiberA <- F.start(ParallelF.value(fa))
+              fiberB <- F.start(ParallelF.value(fb))
+
+              a <- F
+                .onCancel(poll(fiberA.join), F.both(fiberA.cancel, fiberB.cancel).void)
+                .flatMap[A] {
+                  case Outcome.Succeeded(fa) => fa
+                  case Outcome.Errored(e) => fiberB.cancel *> F.raiseError(e)
+                  case Outcome.Canceled() => poll(fiberB.cancel *> F.canceled *> F.never)
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: @djspiewak I don't agree that this `poll` should be here. Can you provide an explanation why?

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: `cancel` is uncancelable, so it has no effect on that segment. The `poll` strictly applies to the `*> F.canceled *> F.never` bit. But of course, if we're canceled while we're trying to cancel ourselves, then clearly there's no problem.

I could see an argument for pushing the `poll` after the `fiberB.cancel`, just so we don't rely on `poll(uncancelable(...))` being gapless.

Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: The `poll(F.canceled *> F.never)` is needed because if this line were `F.canceled *> F.never`, `F.canceled` would be ignored due to the outer `uncancelable`?

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: Yep!

Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: Ok, I am still in favor of moving the `poll` after `fiberB.cancel`.

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala]: After thinking about it, so am I. I think this is probably the last change needed to land this PR!

**Review by djspiewak — APPROVED** [review]
Excellent work!

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 9]
```diff
@@ -53,7 +53,53 @@ trait GenSpawnInstances {
...
         ParallelF(
-          F.both(ParallelF.value(fa), ParallelF.value(fb)).map { case (a, b) => f(a, b) }
+          F.uncancelable { poll =>
+            for {
+              fiberA <- F.start(ParallelF.value(fa))
+              fiberB <- F.start(ParallelF.value(fb))
+
+              a <- F
+                .onCancel(poll(fiberA.join), F.both(fiberA.cancel, fiberB.cancel).void)
+                .flatMap[A] {
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala:63]: Is this type annotation `[A]` (and later `[Z]`) really necessary?

Comment (vasilmkd) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala:63]: It is necessary.

**Review by vasilmkd — APPROVED** [review]
Very impactful change @manufacturist! Amazing contribution. Thank you for your patience while we figured things out along the way. It's usually how great PRs come together. 😄

File: kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala [hunk 10]
```diff
@@ -53,7 +53,53 @@ trait GenSpawnInstances {
       final override def map2[A, B, Z](fa: ParallelF[F, A], fb: ParallelF[F, B])(
```
Comment (johnynek) [inline kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala:53]: this code is exactly the same as below, except for the `Eval` wrapping, no?

Why not have one private method that returns `Now[ParallelF[F, Z]]` and in the map2 case pass `fa, Now(fb)`? I think the extra now wrap unwrap is likely trivial.

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/instances/GenSpawnInstances.scala:53]: > I think the extra now wrap unwrap is likely trivial.

The unwrap is pretty trivial but the allocation is… less so. Particularly since you pay that penalty on a per-item basis.
