### PR TITLE
Simplify Async node

### LINKED ISSUE #1104: Implement Async#promise as a lower level primitive
```scala
trait Async[F[_]] extends Temporal[F] with Sync[F] {
  // ...
  def promise[A]: F[Promise[F, A]]

  def async[A](k: (Either[Throwable, A] => Unit) => F[Option[F[Unit]]]): F[A] =
    promise[A] flatMap { p => 
      k(_.fold(p.fail, p.complete)) flatMap {
        case Some(fin) => p.get.onCancel(fin)
        case None => p.get
      }
    }
}

trait Promise[F[_], A] {
  def fail(t: Throwable): Unit
  def complete(a: A): Unit
  def get: F[A]
}
```

This is a lower level primitive, similar to `Deferred` (but not identical!), which allows us to solve the problem of composable `Async` instances (e.g. #1086). Additionally, this gives us a lot more control over cancelation semantics and radically simplifies concrete implementations, which proves that it's the more primitive version of the concept.

### PR DESCRIPTION
**Pull request by SystemFw**
Fixes  #1104 #1136  #1227

### CODE REVIEW

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 1]
```diff
@@ -705,6 +711,11 @@ object IO extends IOCompanionPlatform with IOLowPriorityImplicits {
   private[effect] final case class Attempt[+A](ioa: IO[A]) extends IO[Either[Throwable, A]] {
     def tag = 20
   }
+  // TODO rename, move
+  private[effect] final case class Cont[A]() extends IO[(IO[A], (Either[Throwable, A] => Unit))] {
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Should be an `object`. Also I would have expected this to outright replace `Async`.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 2]
```diff
@@ -321,6 +325,33 @@ private final class IOFiber[A](
...
+          // If the callback finishes after registration, it owns the
+          // runloops (via async continue), and registration just
+          // terminates in suspendWithFinalizationCheck.
+          // if registration wins, it gets the result from the atomic ref
+          // and it continues, andThen the callback just terminates (stateLoop, when tag == 3)
+          // The rest of the code deals with publication details through
+          // `suspended`, and all the corner cases with finalisation
+          // which we aim to remove with the `promise` construction.
+          // Need to think about naming since resume is already used
+          // all over the place in the runloop.
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: I hope you're not planning on deleting this…

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 3]
```diff
@@ -588,6 +627,81 @@ private final class IOFiber[A](
 
           conts.push(AttemptK)
           runLoop(cur.ioa, nextIteration)
+
+        // Cont TODO rename
+        case 21 =>
+          val state = new AtomicReference[ContState](ContState.Initial)
+
+          val cb: Either[Throwable, A] => Unit = { e =>
+            // should I do any checks on the old finalisation state like in async?
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: The only reason those checks exist is to solve the case where `async` is used *in a finalizer*. When an async callback is fired on a canceled fiber, we generally want to just eat the callback so we don't fork the runloop, but if we're in the process of evaluating finalizers, we *don't* want to eat the callback.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 4]
```diff
@@ -588,6 +627,81 @@ private final class IOFiber[A](
...
+            @tailrec
+            def loop(): Unit = {
+              println(s"cb loop sees suspended ${suspended.get} on fiber $name")
+              if (resume("callback")) { // is this necessary to publish writes?
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: Yes, but also it's necessary to grab the runloop ownership. `suspend`/`resume` are sort of like a runloop semaphore protocol. They're responsible for ensuring that, if someone is running the fiber, there is only *one* such someone.

In this case, what you're doing here is reanimating evaluation of a `get`, so there was a suspension (when the `get` was hit) and now you're bringing it back up again.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 5]
```diff
@@ -588,6 +627,81 @@ private final class IOFiber[A](
...
+          // we want this to be defer and not delay to be able to treat
+          // the result as `null: IO[A]` rather than `null: A`, since
+          // the `null` IO makes the runloop suspend
+          val get: IO[Any] = IO.defer {
+            if (!state.compareAndSet(ContState.Initial, ContState.Waiting)) {
+              // state was no longer Initial, so the callback has already been invoked
+              // and the state is Result
+              val result = state.get().result
+              // we leave the Result state unmodified so that `get` is idempotent
+              if (!shouldFinalize()) {
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: There's probably something awkward here w.r.t. `get` within an `onCancel`.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 6]
```diff
@@ -602,11 +716,19 @@ private final class IOFiber[A](
   private[this] def isUnmasked(): Boolean =
     masks == initMask
 
-  private[this] def resume(): Boolean =
-    suspended.compareAndSet(true, false)
+  private[this] def resume(str: String = ""): Boolean = {
+    val v = suspended.compareAndSet(true, false)
+    if(str.nonEmpty) println(s"resume called by $str on fiber $name, suspended ${suspended.get}")
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: FYI, `str != ""` is a lot faster. `str.length > 0` might be faster-still.

**Review by djspiewak — COMMENTED** [review]
Initial thoughts. I'll stare at the state machine a bit more. Off-hand, it doesn't look like it has enough states to actually work. Need to ponder.

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 1 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: oh sorry, this is just wip. It will replace `Async` once it's done, but I'm keeping both for now so that I can use `start/sleep` in tests and retain a touch of sanity.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 2 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: ahahah I was actually not sure if it was going to be useful for other people or not. But yeah I'm thinking that in the worst case scenario of this PR going nowhere, I'll still commit some of the comments.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 3 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: > the case where async is used in a finalizer

I have to say that this hadn't even remotely crossed my mind, thanks

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 6 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: that's useful thanks, so far I haven't yet hit a case where the slow string check cause the races to disappear,  but it's bound to happen at some point I guess

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 4 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: > . suspend/resume are sort of like a runloop semaphore protocol. They're responsible for ensuring that, if someone is running the fiber, there is only one such someone.

This bit I did get in general, although it breaks with `.get.start` as we've discussed. The reason I added the comment there though is that it seemed to me that `ContState` was going to be enough for that, although that's probably wrong

**Comment by SystemFw** [comment]
> I'll stare at the state machine a bit more. Off-hand, it doesn't look like it has enough states to actually work. Need to ponder.

Please do. Also this construction does not push anything on `conts`, which feels dodgy (but the `async` protocol with respect to `conts` cannot be used here)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 4 above)
Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: I'm worried about things like this:

```scala
promise[A] flatMap { p =>
  p.get.start >> p.get.start
}
```

Like… good luck. You really would need `CallbackQueue` in order to do anything with the above. This is part of why I like the `CPST` approach better, if it works out the way it *seems* like it should.

**Comment by djspiewak** [comment]
> Also this construction does not push anything on conts, which feels dodgy (but the async protocol with respect to conts cannot be used here)

That's actually expected. The only reason `Async` pushes something to `conts` is the fact that it has a *body* (the contents of the `async` block). Of course, `promise` doesn't, so you have no continuations to juggle.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 7]
```diff
@@ -292,6 +292,7 @@ sealed abstract class IO[+A] private () extends IOPlatform[A] {
           poll(ioa.to[F])
 
         case _ : IO.Cont[_] => ??? // TODO rename, translate to operation on Async once it's there
+        case _ : IO.Get[_] => sys.error("impossible")
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IO.scala]: I'm not sure that it is. This is probably similar to the `Unmask` situation

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: yeah actually I think we have a problem here

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: `cont.flatMap(_.get).to[F]` would probably crash, and it's not like `Unmask` either, because in that case we can express the operation as `poll`, I'm not sure we have an equivalent operation in any typeclass here, and putting `get` in `Async` is pretty weird since it's a standalone method, but an internal node which is a by-product of evaluating `Cont`.

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IO.scala]: I think the solution is similar to `Unmask`: you have to get the `get` from the delegate's CPS.

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: mm ok. I'll leave it for now and get back to it once I harden the external encoding

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IO.scala]: > cont.flatMap(_.get).to[F] would probably crash, and it's not like Unmask either, because in that case we can express the operation as poll, I'm not sure we have an equivalent operation in any typeclass here, and putting get in Async is pretty weird since it's a standalone method, but an internal node which is a by-product of evaluating Cont.

You're going to get it *from* the `cont` though. You're starting by interpreting `IO.Cont` to `F`, which you do by calling `F.cont`, which gives you a `get: F[A]`. Take that `get` and stuff it into *another* `IO` node and pass that to the `Cont` function. So you don't have to worry about ever seeing `IO.Get`, but you *will* see your fancy `Get` node that carries the `get: F[A]` value, similar to what we do with `poll` and `Unmask`.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 8]
```diff
@@ -477,17 +510,19 @@ private final class IOFiber[A](
             def apply[B](ioa: IO[B]) = IO.UnmaskRunLoop(ioa, id)
           }
 
+          // The uncancelableK marker is used by `succeeded` and `failed`
+          // to unmask once body completes.
           conts.push(UncancelableK)
           runLoop(cur.body(poll), nextIteration)
 
         // Canceled
         case 12 =>
```
Comment (kubukoz) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:476]: Just wondering, can these be replaced with final vals? Wouldn't they be inlined at compile time?

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:476]: Nope! There are bugs in scalac related to this stuff. Generally-speaking, you can't get a `tableswitch` to generate if you use vals; you need to actually inline the constants manually.

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:476]: (also, curiously, `@inline` appears to *sometimes* fix this issue, but not always; this is, to my knowledge, the only practically visible impact of that annotation)

Comment (kubukoz) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:476]: eh. Thanks ;)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 9]
```diff
@@ -588,6 +627,78 @@ private final class IOFiber[A](
...
+            if (!shouldFinalize()) {
+              // println("get taking over")
+              asyncContinue(result, "get")
+            }
+          } else {
+            // callback has not been invoked yet
+            println(s"get suspending on fiber $name")
+            suspend("get") // async has a conditional suspend, why?
+            println(s"get sets suspended to ${suspended.get} on fiber $name")
+          }
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: I believe this is the origin of the canceled `never` deadlock: you aren't checking `canceled` here. The issue is the fact that cancelation could come in *during* the interpretation of this node, which means the canceler would fail to get the runloop and would thus suspend. Meanwhile, you go through this logic, never check cancelation, and just… suspend, meaning that no one runs the cancelation and things hang forever.

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: ah, I see.
Sounds like the answer to:
> // async has a conditional suspend, why?

and in retrospect, there is this comment in the relevant method too:
>     // race condition check: we may have been cancelled before we suspended

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 10]
```diff
@@ -588,6 +627,79 @@ private final class IOFiber[A](
...
+              //println(s"cb loop sees suspended ${suspended.get} on fiber $name")
+              if (resume("callback")) { // is this necessary to publish writes?
+                if (!shouldFinalize()) {
+                //  println(s"callback taking over on fiber $name")
+                  asyncContinue(e, "callback")
+                }
+              } else if (!shouldFinalize()) {
+//                println(s"callback recurring on fiber $name")
+                loop()
+              } // else println("something wrong")
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: Here's your deadlock. The callback is `resume`ing the fiber, and it *does* need to finalize, but it doesn't have the ability to do so (here it just drops things on the floor). The scenario happens in the following case:

1. `get` suspends
2. The callback is fired and we pass through the `resume` barrier
3. Some other fiber cancels the `get`, and `cancel` cannot `resume`
4. The above block is hit, meaning that we have detected that we need to finalize, but no one ran the finalizers *for* us (and they can't, since we own the runloop), so we just die.

`Async` has quite a lot of complex conditional double-checking to avoid this particular scenario. :-)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 9 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: This fixed it

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 10 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: After adding some tracing, deadlock doesn't happen on a winning callback path, it seems

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 11]
```diff
@@ -588,6 +627,79 @@ private final class IOFiber[A](
...
+
+          if (!state.compareAndSet(ContState.Initial, ContState.Waiting)) {
+            // state was no longer Initial, so the callback has already been invoked
+            // and the state is Result
+            val result = state.get().result
+            // we leave the Result state unmodified so that `get` is idempotent
+            if (!shouldFinalize()) {
+              // println("get taking over")
+              asyncContinue(result, "get")
+            }
```
Comment (SystemFw) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: It's actually here, it hits the (invisible) `else`

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 10 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Ok I fixed the deadlock, which was a similar case but in `get`. This specific path isn't stressed by any tests, but I think you're right, basically on line 644 you need `else cancel`

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 3 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: does this check apply to the callback in promise as well then?

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: it appears to not be needed: removing it when using `Async` makes a test consistently fail, and that same test consistently passes when using `Cont/promise`

File: kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala [hunk 12]
```diff
@@ -175,11 +175,12 @@ object Deferred {
...
-              val id = addReader(awakeReader = resume)
-              val onCancel = F.delay(deleteReader(id))
+               val resume = (a: A) => cb(Right(a))
 
-              onCancel.some.pure[F]
+              F.delay(addReader(awakeReader = resume)).map { id =>
+                // if canceled
+                F.delay(deleteReader(id)).some
+              }
             }
```
Comment (SystemFw) [inline kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala:170]: I'm using `async` as we've agreed here, just wanted to double check we are ok with the extra allocations

File: core/js/src/main/scala/cats/effect/IOFiberConstants.scala [hunk 13]
```diff
@@ -26,7 +26,7 @@ private[effect] object IOFiberConstants {
   val FlatMapK: Byte = 1
   val CancelationLoopK: Byte = 2
   val RunTerminusK: Byte = 3
-  val AsyncK: Byte = 4
+  // TODO reassign tags after AsyncK removal
```
Comment (djspiewak) [inline core/js/src/main/scala/cats/effect/IOFiberConstants.scala]: FYI the tag reassignment is quite important. :-) `tableswitch` with consecutive values is treated differently by HotSpot than non-consecutive ones.

File: kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala (hunk 12 above)
Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala:170]: I think we can loop back and rework it if we decide that's worthwhile. There are definitely performance advantage to working with `cont` directly, but they might disappear when we fiddle with the API to be safer.

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Deferred.scala:170]: yeah fair enough. The side-effects in the old usage are a lot scarier imho now that `async` is not primitive, there are a lot more layers from there to execution

File: core/js/src/main/scala/cats/effect/IOFiberConstants.scala (hunk 13 above)
Comment (SystemFw) [reply core/js/src/main/scala/cats/effect/IOFiberConstants.scala]: oh wow. Btw once I get there, I really want to also cluster the operations differently, so switching order in `IOFiber` and `IO`. This might be annoying for people hacking on it so I'll check on gitter before starting, but I do think it will make `IOFiber` easier to digest.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 14]
```diff
@@ -595,6 +513,146 @@ private final class IOFiber[A](
...
+          val cur = cur0.asInstanceOf[Get[Any]]
+          val state = cur.state
+
+            if (state.compareAndSet(ContStateInitial, ContStateWaiting)) {
+              // `state` was Initial, so `get` has arrived before the callback,
+              // needs to set to waiting and suspend: cb will resume with the result
+              // once that's ready
+
+              // full memory barrier
+              suspended.compareAndSet(false, true)
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: We were talking about this on Gitter earlier, but to reiterate why this was done (and to jog my memory about it). A CAS has the effect of both a volatile read and write, and so the non-volatile invariant extends here as well. Specifically, we want to observe the most up-to-date value of `cancelled`.

Additionally, this CAS should *always* succeed because the runloop is owned by the current thread.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 5 above)
Comment (RaasAhsan) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: If we're running finalizers, that means `asyncCancel` was invoked at some point, which masks the runloop. If we're masked, `shouldFinalize()` evaluates to `false`, so we would proceed with `asyncContinue` in this case. In general, once we start finalization, subsequent calls to `shouldFinalize()` will always return `false`.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 15]
```diff
@@ -595,6 +513,146 @@ private final class IOFiber[A](
...
+
+          val get: IO[Any] = IO.Get(state)
+          val cont = (get, cb)
+
+          runLoop(succeeded(cont, 0),  nextIteration)
+        case 22 =>
+          val cur = cur0.asInstanceOf[Get[Any]]
+          val state = cur.state
+
+            if (state.compareAndSet(ContStateInitial, ContStateWaiting)) {
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: extra indentation here?

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 16]
```diff
@@ -595,6 +513,146 @@ private final class IOFiber[A](
...
+            }
+
+            stateLoop()
+          }
+
+          val get: IO[Any] = IO.Get(state)
+          val cont = (get, cb)
+
+          runLoop(succeeded(cont, 0),  nextIteration)
+        case 22 =>
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: 1. What is the effect of sequencing the same `get` multiple times? 
2. Do several invocations of `cont` interact with each other as expected with various interleavings of `get` and `resume`? 

I think its worth having test cases for these but feel free to open a follow up issue :)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 17]
```diff
@@ -595,6 +513,146 @@ private final class IOFiber[A](
...
+             * and is waiting for a result (i.e. it has suspended),
+             * acquire runloop to continue.
+             *
+             * If not, `cb` arrived first, so it just sets the result and die off.
+             *
+             * If `state` is `Result`, the callback has been already invoked, so no-op.
+             * (guards from double calls)
+             */
+            @tailrec
+            def stateLoop(): Unit = {
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:441]: I was expecting otherwise, but it's interesting that this `stateLoop` stayed mostly intact from the old `Async`. I think that goes to say that old finalizer registration mechanism was just a more specific variant of what we have now

**Review by RaasAhsan — COMMENTED** [review]
This is looking awesome, and much easier to understand!

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 14 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: I'm going to expand that comment a bit to include some of this

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 16 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: 1. Should be idempotent
2. I don't know, and this is worth checking to make sure there are no weird interactions. On one hand the number of interleavings is reduced by not being able to `start` `get`, but on the other I expect it to be fully possible to misuse this to deadlock (in a way that we cannot prevent). But still, worth checking that in sane usage we aren't messing up the runloop somehow

**Comment by djspiewak** [comment]
I find it interesting that you seem to dislike line comments :-)

**Comment by SystemFw** [comment]
> I find it interesting that you seem to dislike line comments :-)

I don't really. In this case I disliked having the debug printlns that I need to glance over interwoven with the stuff I need to read. So I started by adding `// LOG` to those lines, but then I moved to this commit. Not sure if I like the result or not (interlude: this is part of why I like working with granular commits and really avoid squashing on merge)

**Comment by djspiewak** [comment]
> (interlude: this is part of why I like working with granular commits and really avoid squashing on merge)

Hard agree

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala [hunk 18]
```diff
@@ -0,0 +1,85 @@
...
+ */
+
+package cats.effect.kernel
+package internal
+
+import cats.syntax.all._
+import cats.arrow.FunctionK
+import java.util.concurrent.atomic.AtomicReference
+
+private[kernel] final class DefaultCont[F[_], A](implicit F: Async[F]) {
```
Comment (SystemFw) [inline kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: There's an interesting question as to how to test this

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: Maybe create an identity transformer which sits on top of `IO` but delegates to `IO`'s `async` rather than its `cont`?

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: and then run the entire IOSpec over that? that's fair enough, although ultimately it's still running on top of `IOCont`, which `IO.async` sits on top of

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: Yeah, but if we trust `IOCont`, then we trust its derived `async`

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 19]
```diff
@@ -376,20 +364,28 @@ object IO extends IOCompanionPlatform with IOLowPriorityImplicits {
...
-    async(cb => apply { k(cb); None })
+    effectForIO.async_(k)
 
   def canceled: IO[Unit] = Canceled
 
   def cede: IO[Unit] = Cede
 
+  /**
+   * This is a low-level API which is meant for implementors,
+   * please use `start`, `async` or `Deferred` instead,
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Should we recommend `background` here instead

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 20]
```diff
@@ -72,209 +74,135 @@ private final class IOFiber[A](
...
-    } else {
-      if (cb != null)
-        cb(RightUnit)
-
-      done(OutcomeCanceled)
-    }
-  }
-
-  // masks encoding: initMask => no masks, ++ => push, -- => pop
+  /* masks encoding: initMask => no masks, ++ => push, -- => pop */
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:193]: is this supposed to be somewhere else

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 21]
```diff
@@ -313,192 +275,267 @@ private final class IOFiber[A](
...
+            def loop(): Unit = {
+              // println(s"cb loop sees suspended ${suspended.get} on fiber $name")
+              /* try to take ownership of the runloop */
               if (resume()) {
-                state.lazySet(AsyncStateDone) // avoid leaks
-
-                // Race condition check:
-                // If finalization occurs and an async finalizer suspends the runloop,
-                // a window is created where a normal async resumes the runloop.
-                if (finalizing == wasFinalizing) {
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: This check was rather crucial: if a fiber is suspended in an asynchronous boundary and gets cancelled, the canceller will acquire the runloop and finalize. If one of the finalizers are asynchronous, the canceller enters an asynchronous boundary. At this point, if the callback from the *original* async completes, it's going to be able to acquire runloop, and try to apply the continuation on top of the stack to the result, which ultimately throws an exception.

If this isn't necessary anymore, we can remove the `finalizing` instance variable.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 22]
```diff
@@ -313,192 +275,267 @@ private final class IOFiber[A](
...
-          val cur = cur0.asInstanceOf[Map[Any, Any]]
+          val get: IO[Any] = IOCont
+            .Get(state)
+            .onCancel(
+              /*
+               * If get gets canceled but the result hasn't been computed yet,
+               * restore the state to Initial to ensure a subsequent `Get` in
+               * a finalizer still works with the same logic.
+               */
+              IO(state.compareAndSet(ContStateWaiting, ContStateInitial)).void
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:469]: ooh, this is a really good catch

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 23]
```diff
@@ -567,42 +604,138 @@ private final class IOFiber[A](
...
+    } finally {
+      callbacks.lazySet(null) // avoid leaks
+    }
+
+    /*
+     * need to reset masks to 0 to terminate async callbacks
+     * busy spinning in `loop`.
+     */
+    masks = initMask
+    /* full memory barrier to publish masks */
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: I wrote this but it's wrong BTW, it's just a write barrier. 

Also, the reason this was added in: with the old `Async` state machine, after `Async` registered a finalizer and suspended, somebody else could `cancel` before the callback can acquire the runloop. In that scenario, the callback perpetually loops since the canceller owns the runloop now and masks before finalizing. 

After cancellation and finalizations completes, we reset `masks` which signals to the callback loop that the current fiber is both cancelled and completely unmasked, so somebody else handled cancellation. So the `!shouldFinalize()` check in `loop` fails, which terminates it

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 24]
```diff
@@ -567,42 +604,138 @@ private final class IOFiber[A](
...
+    asyncContinueEither = null
+    blockingCur = null
+    afterBlockingSuccessfulResult = null
+    afterBlockingFailedError = null
+    evalOnIOA = null
+    resumeTag = DoneR
+  }
+
+  /*
+   4 possible cases for callback and cancellation:
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: I added this in awhile back, I think i came to the conclusion that this is wrong or just incomplete. But this behavior is better described by your new comments now :)

**Review by RaasAhsan — COMMENTED** [review]
reviewed half of it, going to look at the rest tomorrow

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 20 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:193]: It was there before my changes as well. Not quite sure where to put it, it's a general point, which affects `childMask`, `initMask`, `masks`, `case 9` and `case 10` in the runloop (that's a candidate spot), `isUnmasked`, etc

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 21 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: I need to think more about whether this is still needed or not. Please do the same :)
The reason I removed it is that with the old `async`, removing the check causes a test to consistently fail, and with `cont` (without the check), the same test consistently succeeds
https://github.com/typelevel/cats-effect/pull/1165#discussion_r492684017

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: If/when we all agree it's not needed, I'll go ahead and remove `finalizing`, thanks for pointing that out

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 22 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:469]: The solution here was surprisingly simple, I had gone down a really complicated avenue of double checking AtomicReferences before realising I could use `IO` itself and `onCancel`. This is the solution to "`get` within an `onCancel`" bug, ftr.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 23 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: What should I do here? Delete the full memory barrier comment for sure. Should I also add your comment above? is it still needed?

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 24 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Will delete then, cheers

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 19 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: yeah I will mention it there

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IO.scala]: Also oxford comma please :-)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 21 above)
Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: `"run the continuation of an async finalizer within async"` in `IOSpec` proves that this isn't necessary any longer, though it isn't immediately obvious to me *why* it is no longer necessary.

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 19 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IO.scala]: I actually love Oxford commas

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 21 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: >  though it isn't immediately obvious to me why it is no longer necessary.

Exactly :)

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 19 above)
Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IO.scala]: They make lists so much less ambiguous

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 23 above)
Comment (RaasAhsan) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Yeah, I believe it's still needed, I just wanted to make sure you and others are aware of why it's being done because it's not entirely clear (I had to spend 15 minutes recalling). Here's the race it fixes to be more clear:
1. Fiber A starts the `Cont` action.
2. Fiber A invokes `Cont.get`, which sets the `AtomicReference` to `ContStateWaiting`.
3. Before Fiber A suspends, the `Cont` action invokes the callback, and sets the `AtomicReference` to `ContStateResult`, and moves to `loop` to acquire the runloop, but it can't yet because fiber A hasn't suspended yet.
4. Fiber A suspends.
5. Fiber B cancels fiber A. Before the callback manages to acquire the runloop, B acquires the runloop, masks, finalization and terminates the fiber. At this point, assume we're not unmasking or publishing that state via `suspended`.
6. The callback for the `Cont` action is stuck in an infinite loop: it can't reacquire the runloop since it will never be released again, and the `!shouldFinalize()` will always pass because we're still masked.

So, by resetting `masks` and publishing that state, we can force that `!shouldFinalize` check to fail, which lets `loop` end.

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Fantastic, I'll see if I can work that in a comment somewhere

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 21 above)
Comment (RaasAhsan) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: IIRC this was definitely a racey behavior that I observed for some test case over millions of invocations. So, I think there are two possible races here, one of which the finalizer on `Get` actually fixes:
1. Fiber A starts the `Cont` action.
2. Fiber A invokes `get`, suspending the runloop.
3. Fiber B cancels A, so it acquires A's runloop and starts finalization. The first finalizer is *guaranteed* to be the one registered over `Get`! So this resets the `AtomicReference` back to the `Initial` state.
4. B encounters an async finalizer for A, so it suspends the runloop. We will never encounter an async finalizer before the one over `Get`.
5. The callback from step 1 completes. It sees the `Initial` state so transitions to `Result` and exits out.

Here's an example of a race that it doesn't fix:
1. Fiber A starts the `Cont` action.
2. Fiber A calls `Get`, setting the `AtomicReference` to `Waiting`.
3. Before A suspends the runloop, the callback from step 1 completes. It sees the `Waiting` state, transitions to `Result`, and then tries to acquire the runloop in `loop`, which it can't at this point, so it loops.
4. A suspends the runloop.
5. Fiber B cancels A, acquiring the runloop. It begins finalization. The first finalizer resets the `AtomicReference` to `Initial`, as described above.
6. B encounters an async finalizer for A, so it suspends.
7. The callback from step 1 reacquires the runloop in `loop`. `!shouldFinalize()` evaluates to true because we are masked, so it moves onto `asyncContinue` which is where everything starts to break down.

I think that's right, but please double check that :D I wonder if there's a more obvious way to represent and compare against this fiber state, but it's not immediately obvious to me yet

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:370]: I believe this is correct. It's a much more subtle and harder to hit case than the original one, but I believe the analysis is accurate that we don't handle it without checking that we're in the same finalization state as when we started.

As a note, we only need two finalization states because finalizers themselves are not cancelable. So we can only generate this scenario at a single level.

File: kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala [hunk 25]
```diff
@@ -0,0 +1,72 @@
...
+ * operations up to `MonadCancel` (`flatMap`, `onCancel`, `uncancelable`, etc).
+ *
+ * If you are an implementor, and you have an implementation of `async` but not `cont`,
+ * you can override `Async[F].async` with your implementation, and use `Async.defaultCont`
+ * to implement `Async[F].cont`.
+ */
+trait Cont[F[_], A] {
+  def apply[G[_]](
+      implicit
+      G: MonadCancel[G, Throwable]): (Either[Throwable, A] => Unit, G[A], F ~> G) => G[A]
```
Comment (djspiewak) [inline kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala:71]: Why not:

```scala
  def apply[G[_]](
      resume: Either[Throwable, A] => Unit,
      get: G[A],
      lift: F ~> G)(
      implicit G: MonadCancel[G, Throwable]): G[A]
```

More names and easier syntax at call sites.

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala:71]: > More names and easier syntax at call sites.

That's what I used to have, but actually the call site with that is _so_ much uglier

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala:71]: https://github.com/typelevel/cats-effect/pull/1165/commits/d2d23a2513cdb53b0ac573e132ae53c7e9c520c1#diff-8d42a1f7ffbea3d266c76d171c65d92c

have a look, note how many type signatures we can omit

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala:71]: Also I think the higher-rank type is clearer this way, although probably the only one who'll ever notice is me :P

Comment (djspiewak) [reply kernel/shared/src/main/scala/cats/effect/kernel/Cont.scala:71]: Ah I see what you mean. Okay that's fair.

And yeah, I do think the higher-rank is clearer. That's actually the very first thing I noticed. :-) Had to stare at it a while to convince myself that it was actually okay to do what I was proposing. We can leave it as-is then.

File: kernel/shared/src/main/scala/cats/effect/kernel/Async.scala [hunk 26]
```diff
@@ -40,8 +53,21 @@ trait Async[F[_]] extends AsyncPlatform[F] with Sync[F] with Temporal[F] {
...
+   * provides an implementation of `cont` in terms of `async`.
+   * Note that if you use `defaultCont` you _have_ to override `async`.
+   */
+  def cont[A](body: Cont[F, A]): F[A]
 }
 
 object Async {
   def apply[F[_]](implicit F: Async[F]): F.type = F
+
+  def defaultCont[F[_]: Async, A](body: Cont[F, A]): F[A] =
```
Comment (djspiewak) [inline kernel/shared/src/main/scala/cats/effect/kernel/Async.scala]: If we make this `protected`, will subclasses of the companion trait be able to see it? That would be ideal, imo.

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala [hunk 27]
```diff
@@ -0,0 +1,89 @@
...
+    loop()
+  }
+}
+private[kernel] object DefaultCont {
+  sealed trait State[A]
+  case class Initial[A]() extends State[A]
+  case class Value[A](v: Either[Throwable, A]) extends State[A]
+  case class Waiting[A](cb: Either[Throwable, A] => Unit) extends State[A]
+
+  def cont[F[_]: Async, A](body: Cont[F, A]): F[A] =
```
Comment (djspiewak) [inline kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: IMO it actually would be nicer to just inline this into `Async.defaultCont`. The types here don't serve any purpose other than redirecting the implementation to another file.

**Review by djspiewak — CHANGES_REQUESTED** [review]

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 28]
```diff
@@ -313,192 +275,285 @@ private final class IOFiber[A](
...
+              // println(s"cb loop sees suspended ${suspended.get} on fiber $name")
+              /* try to take ownership of the runloop */
               if (resume()) {
-                state.lazySet(AsyncStateDone) // avoid leaks
-
-                // Race condition check:
-                // If finalization occurs and an async finalizer suspends the runloop,
-                // a window is created where a normal async resumes the runloop.
-                if (finalizing == wasFinalizing) {
+                if (finalizing == wasFinalizing.get()) {
```
Comment (RaasAhsan) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:392]: I *think* this looks good to me, will keep on thinking about it. Here's an alternative state coordination mechanism that makes somewhat more sense to me:
1. Renaming `wasFinalizing` to `waiting`. The purpose of this variable is to communicate to the callback whether the fiber is ready to resume from *this* callback specifically.
2. Add an extra statement to the `Get` finalizer that sets `waiting` to false.
3. Replace this conditional with `waiting.get()`. This basically indicates that the runloop suspended with the intention if waiting on this fiber. 
4. We can remove the `finalizing` field member.

If it's actually correct, I think this mechanism is slightly easier to understand, since it's completely independent of finalization. It's "if the runloop is waiting on me, then I can proceed" rather than "if the current runloop finalization state is the same as the state of whoever is currently waiting".

File: core/shared/src/test/scala/cats/effect/ContSpec.scala [hunk 29]
```diff
@@ -0,0 +1,211 @@
...
+    val io = cont {
+      new Cont[IO, Int] {
+        def apply[F[_]: Cancelable] = { (resume, get, lift) =>
+          lift(IO(scheduler.sleep(10.millis, () => resume(Right(42))))) >> get >> get
+        }
+
+      }
+    }
+
+    val test = io.flatMap(r => IO(r mustEqual 42))
```
Comment (RaasAhsan) [inline core/shared/src/test/scala/cats/effect/ContSpec.scala:207]: I think it would be nice to have tests that involve multiple `cont` calls with different orderings of `resume`/`get`. Let me know if I should just do it, would be a good opportunity to play around with this :)

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala [hunk 30]
```diff
@@ -0,0 +1,89 @@
...
+
+  def get: F[A] =
+    F.defer {
+      state.get match {
+        case Value(v) => F.fromEither(v)
+        case Initial() =>
+          F.async { cb =>
+            val waiting = Waiting(cb)
+
+            def loop(): Unit =
```
Comment (RaasAhsan) [inline kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: `@tailrec` here just to be safe ?

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala [hunk 31]
```diff
@@ -0,0 +1,89 @@
...
+           * - if a previous `get` has been interrupted and we are running as part of
+           *   its finalisers, the state would have been either restored to `Initial`
+           *   by the finaliser of that `get`, or set to `Value` by `resume`
+           */
+          sys.error("Impossible")
+      }
+    }
+
+  def resume(v: Either[Throwable, A]): Unit = {
+    def loop(): Unit =
```
Comment (RaasAhsan) [inline kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: `tailrec` here as well

File: core/shared/src/test/scala/cats/effect/ContSpec.scala (hunk 29 above)
Comment (SystemFw) [reply core/shared/src/test/scala/cats/effect/ContSpec.scala:207]: Go for it

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala (hunk 30 above)
Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: solved in the next commit, for some reason the diff doesn't show it

File: kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala (hunk 27 above)
Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/internal/DefaultCont.scala]: yeah ok will do that

File: kernel/shared/src/main/scala/cats/effect/kernel/Async.scala (hunk 26 above)
Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Async.scala]:
```
trait A
object A {
  protected def a = 1
}

trait B extends A {
  def b = A.a
}

method a in object A cannot be accessed in object A
[error]  Access to protected method a not permitted because
[error]  enclosing trait B is not a subclass of
[error]  object A where target is defined
[error]   def b = A.a
```

Comment (SystemFw) [reply kernel/shared/src/main/scala/cats/effect/kernel/Async.scala]: > method a in object A cannot be accessed in object A

it would be a good scala trivia to ask what code can generate this error lol

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 28 above)
Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:392]: I find the solution in the PR (and the one in the old async) a bit opaque.
I _think_ I prefer the direction with the `id` of the suspension, which acts as a sort of epoch number, because I think the specific problem is more accurately described as "we don't want a callback of a previous epoch to resume the runloop in a new epoch", with an orthogonal statement that says "a change of epoch happens during finalisation, in the presence of an async finaliser"

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:392]: I think that @RaasAhsan's proposed solution is even *better* than the epoch number, actually, since we only need an epoch bit and his solution achieves it while removing the extra state from `IOFiber` itself. I really like that, but I think we should implement it in a follow-up PR.

The solution currently on the branch is definitely opaque, I just want to get this landed in a functional form so that we can unblock everything else. :-D

Comment (SystemFw) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:392]: I'm fixing the conflicts as we speak, let's get it merged and then @RaasAhsan can add his solution and the additional tests in a follow up
