### PR TITLE
dispatcher releasing itself rejects new tasks

### LINKED ISSUE #3501: Closing a `Dispatcher` from within it seems to enter invalid state (?)
Consider this snippet.
```scala
//> using lib "org.typelevel::cats-effect::3.5.0-RC3"

import cats.effect._
import cats.effect.std.Dispatcher

import scala.concurrent.duration._

object App extends IOApp.Simple {
  // same result with sequential
  def run = Dispatcher.parallel[IO].allocated.flatMap {
    case (dispatcher, release) =>
      IO(dispatcher.unsafeRunAndForget(release)) *>
        IO.sleep(100.millis) *>
        IO(dispatcher.unsafeRunAndForget(IO.println("please don't print"))) *>
        IO.sleep(100.millis) *>
        IO.println("huh")
  }
}
```

What that's doing is starting a `Dispatcher`, and then attempting to close that dispatcher by submitting the close action to it.

When I tried this I wasn't entirely sure what to expect: `release` will block until the `Dispatcher` cancels all ongoing tasks. But one of those ongoing tasks is canceling the `Dispatcher`, which is blocked ... 🤔 so I thought this would either deadlock or the release would be `canceled`.

Well, it doesn't deadlock. But also the `Dispatcher` no long appears to work e.g. the `IO.println(...)` doesn't print. _But_ it still allows to submit tasks to it, instead of raising an `java.lang.IllegalStateException: dispatcher already shutdown`.

So it's in this weird state, where nothing is running but shutdown somehow hasn't completed.

### PR DESCRIPTION
**Pull request by samspills**
resolves #3501 

- adds a test to confirm that an illegal state exception is raised when attempting to submit tasks to a dispatcher after we've already submitted its own release action as a task
- confirmed that if I move the `alive` release in `Dispatcher` from line 315 up to 245, this test fails for sequential dispatchers
- I replicated the test 1000 times and it passed so I think 100 milliseconds is enough time for the parallel case and this won't be flaky. 

(I wasn't sure about release plans so I branched off of 3.x? This is just a test so not super important for releasing but let me know if I should switch the branch)

### CODE REVIEW

**Review by armanbilge — DISMISSED** [review]
Thank you Sam!

**Comment by armanbilge** [comment]
I'm confused about this "reject new tasks while shutting down" flake ... seems to have flaked with the exact exception we are looking for?

https://cirrus-ci.com/task/4538803671531520?logs=main#L3252

**Comment by samspills** [comment]
The failing test in CI is the IO timeoutTo test, which I think should already be fixed in 3.x. I'll double check that my branch is up to date before rerunning tests again (just going to be a little bit as I'm afk right now)

**Comment by samspills** [comment]
Oh I didn't even look at that one!! Thanks for pointing that out Arman, I'll investigate that as well. It does seem weird...

**Comment by armanbilge** [comment]
> The failing test in CI is the IO timeoutTo test, which I think should already be fixed in 3.x. I'll double check that my branch is up to date

Yeah, I just commented on https://github.com/typelevel/cats-effect/issues/3568#issuecomment-1528831131. You're not behind—CI runs on a synthetic merge commit so it is always up-to-date with the target branch at time of opening the PR. (This is also why the close-reopen trick re-triggers CI with a fresh merge that includes any new changes on the target branch.)

**Comment by samspills** [comment]
I was able to reproduce the cirrus failure locally:
```
[error]     x reject new tasks while shutting down
[error]      Left(java.lang.IllegalStateException: dispatcher already shutdown) is not Right (DispatcherSpec.scala:352)
```

it seems pretty rare. The issue is that the rogue task is enqueued but then the second `alive` check in `unsafeToFutureCancelable` fails, which tries to cancel the task and raises the exception: https://github.com/typelevel/cats-effect/blob/38736ca1e35cf79eb6345bc65768b2d2ab5bc375/std/shared/src/main/scala/cats/effect/std/Dispatcher.scala#L414-L420

Since the task here is so trivial, it's already finished so we end up in a situation where the task was completed even though the submission of it failed. I'm still working on addressing it.

File: tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala [hunk 1]
```diff
@@ -346,10 +346,9 @@ class DispatcherSpec extends BaseSpec with DetectPlatform {
                   result <- resultR.get
                   rogueResult <- rogueResultR.get
                   _ <- IO(result must beTrue)
-                  _ <- IO(rogueResult match {
-                    // if the rogue task is not completed then we _must_ have failed to submit it
-                    case false => rogueSubmitResult must beLeft
-                    case true => rogueSubmitResult must beRight
+                  _ <- IO(if (rogueResult == false) {
+                    // if the rogue task is not completed then we must have failed to submit it
+                    rogueSubmitResult must beLeft
```
Comment (samspills) [inline tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala:351]: As mentioned in my earlier comment, the previous version of this test could fail because the task was enqueued+completed but the submission of it actually failed during the final `alive` check. 

To deal with this I've tried to further reduce the scope of this test. I think all we want to test is that a task is not successfully submitted during the shutdown process. This was still the case for the previous failure (the submission failed! it's just that our task is so trivial that it was already finished instead of being cancelled) but the way the test was written treated it as a failure.

Arman and I are still chatting about the alive check and the task enqueueing, but that's definitely a different PR

**Review by djspiewak — APPROVED** [review]
