### PR TITLE
Fix the spinlock from #4377 and probably also fix #4448

### LINKED ISSUE #4448: Poisoned pod, extremely slow, weird thread counts
Our pods (hosted in kubernetes)  sometimes get poisoned and 100% of their requests become incredibly slow (think 5-25secs instead of <1s). 
Response is slow even with zero traffic (essentially only test curl).
Non poisioned pod from same deployment works just fine (and has normal numbers in jmx etc).

interesting jmx of poisioned pod
```
ComputePoolSampler.ActiveThreadCount is 65534 
ComputePoolSampler.WorkerThreadCount is 2
ComputePoolSampler.SearchingThreadCount is 65535. 
ComputePoolSampler.BlockedWorkerThreadCount is 0
```
Weirdly threaddump shows < 100threads. [threads_dump.txt](https://github.com/user-attachments/files/21330624/threads_dump.txt)

```
scala2.13.6
cats-effect: 3.6.2
doobie 1.0.0-RC9
sttp client with armeria backend 3.11.0
tapir + http4s 1.11.36

```

```
vm 17.0.15 eclipse adoptium (observed also on 21)

jvm options
 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Djava.rmi.server.hostname=127.0.0.1 -XX:+UseG1GC -XX:G1PeriodicGCInterval=30000 -XX:+PrintCommandLineFlags -Dsun.net.inetaddr.ttl=30 -Dpidfile.path=/dev/null -XX:+CrashOnOutOfMemoryError -XX:MaxMetaspaceSize=320m -XX:ReservedCodeCacheSize=64m -XX:CompressedClassSpaceSize=64m -XX:InitialHeapSize=519m -XX:MaxHeapSize=1038m
-XX:CompressedClassSpaceSize=67108864 -XX:ConcGCThreads=1 -XX:+CrashOnOutOfMemoryError -XX:G1ConcRefinementThreads=2 -XX:G1PeriodicGCInterval=30000 -XX:GCDrainStackTargetSize=64 -XX:InitialHeapSize=544210944 -XX:+ManagementServer -XX:MarkStackSize=4194304 -XX:MaxHeapSize=1088421888 -XX:MaxMetaspaceSize=335544320 -XX:MinHeapSize=6815736 -XX:+PrintCommandLineFlags -XX:ReservedCodeCacheSize=67108864 -XX:-THPStackMitigation -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC
```

If we kill the pod the new one works just fine, but roughly once a day we see this happen on eventually on multiple pods across multiple services, where only commonality is cats-effect 3.6.2, latest scala2, tapir and sttp client, doobie rc9 (though not necessarily the same client/server backends).

k8 instances
```
 limits:
            cpu: 1100m
            memory: 1200Mi
          requests:
            cpu: 600m
            memory: 1200Mi
```

Some pods never get poisoned, we haven't yet observed any pattern except that it happens semi-regularly, and once it's poisioned it doesn't recover.

### PR DESCRIPTION
**Pull request by durban**
So, #4377 added a spinlock for interrupting a sleeping/polling WorkerThread. That spinlock is incorrect, i.e., a worker thread doesn't necessarily waits (spins) until the spinlock is released by WSTP#notifyParked. The incorrect scenario is when the worker thread observes `parked` being "parked", tries to CAS it to "unparked", and the CAS fails. The current implementation in this case simply goes on, as if the lock is free. While in fact it may not be free; it's likely that the CAS failed exactly because the spinlock was acquired.

This PR fixes the spinlock, so in this case the worker thread re-reads `parked`, and correctly waits for the lock to be free.

Now, I think this is the reason for the bug #4448. I think what happens there is that the worker thread goes on while the spinlock is locked by WSTP#notifyParked; the worker thread goes to sleep (`parked` becomes "parked"); WSTP#notifyParked "releases" the lock it thinks it still holds, thus `parked` changes state directly from "parked" -> "unparked", _without a corresponding doneSleeping_ (in normal (correct) operation, a doneSleeping call is always made when `parked` moves out from "parked"). Thus, a `doneSleeping` call is, in effect "missing". The `state` 0xfffeffff[^1] observed in #4448 is exactly the missing doneSleeping call (i.e., `-DeltaSearching`).

That's why I believe this should fix #4448. I don't know how to write a test for that (the only way I could observe the issue locally is by putting `Thread.yield`s in various places in the WSTP). However, I believe the occasional `MutexSpec` failures were exactly because of this problem.

[^1]: 0xfffeffff is the (65534, 65535) = (ActiveThreadCount, SearchingThreadCount) reported in #4448.

### CODE REVIEW

**Comment by durban** [comment]
Btw, in #4377 I've asked why the spinlock is necessary (I dislike spinlocks ;-). @djspiewak said (more or less), that due to `doneSleeping`. I think this issue proves, that @djspiewak was right, since the spinlock being incorrect caused a bug with `doneSleeping`. (Although, I still think that it would be possible to avoid the spinlock by _always_ carefully CASing `parked`, let's fix this first, then possibly later we might figure out how exactly to remove the lock :-)

**Comment by djspiewak** [comment]
> I've asked why the spinlock is necessary (I dislike spinlocks ;-)

What did spinlocks ever do to you?! :P

More seriously, the async bounded and unbounded queue implementations are a pretty fun one to look at from this standpoint. They're lock free MPMC structures, and what's interesting is they *require* a spinlock in a very very specific circumstance. It's somewhat similar to the `parked` case, where you have two bits of atomic state and sometimes you can detect them in a mutually inconsistent state, but you know that when that happens, you're just seeing the state a few cycles before the other CPU publishes its results, so you just have to chill out for a second and wait for the memory bus to do its thing. The only alternative would be to have a hard thread lock, which effectively does something very similar but indirectly in the kernel, so nothing is really gained.

**Review by djspiewak — DISMISSED** [review]
Oh this is a really nice catch. I'm not sure why I didn't think concurrent interruption was possible but obviously that's an issue.

**Comment by durban** [comment]
> They're lock free MPMC structures, and what's interesting is they _require_ a spinlock

If they require a spinlock, they're not lock free :P

**Comment by djspiewak** [comment]
> If they require a spinlock, they're not lock free :P

*Mostly* lock-free! :D But in fairness, I think that's pretty much everything. There are no *truly* lock-free concurrent systems, only systems which marginalize locks to extremely rare cases involving composite atomics.

**Comment by durban** [comment]
I mean... a MPMC queue can definitely be lock free. The one using the spinlock is possibly faster, but there is no theoretical or even practical obstacle to making it lock free (i.e., using a spinlock in rare cases will probably make it faster than using an algorithm that never uses a lock... but that algorithm still exists, and could be used...).

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala [hunk 1]
```diff
@@ -645,9 +646,15 @@ private[effect] final class WorkerThread[P <: AnyRef](
...
           while (parked.get() eq ParkedSignal.Interrupting) {}
-        } else if (parked.compareAndSet(st, ParkedSignal.Unparked)) {
-          // we won the race to awaken ourselves, so we need to let the pool know
-          pool.doneSleeping()
+        } else {
+          if (parked.compareAndSet(st, ParkedSignal.Unparked)) {
+            // we won the race to awaken ourselves, so we need to let the pool know
+            pool.doneSleeping()
+          } else {
+            // lost CAS race, possibly concurrent `Interrupting``,
```
Comment (mr-git) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]:
```suggestion
            // lost CAS race, possibly concurrent `Interrupting`,
```

**Review by djspiewak — APPROVED** [review]
