### PR TITLE
Converted startup runtime collision into a warning

### LINKED ISSUE #1918: Initialization error when using unsafe.implicits.global within IOApp
While updating some examples that demonstrate what *not to do*, I bumped into this issue. Here's my example.

```scala
import scala.concurrent.duration._

import cats.effect._
import cats.effect.std.{ Semaphore, Supervisor }
import cats.effect.unsafe.implicits.global

object LeakyState extends IOApp.Simple {

  // global access
  val sem: Semaphore[IO] =
    Semaphore[IO](1).unsafeRunSync()

  def launchMissiles: IO[Unit] =
    sem.permit
      .use { _ =>
        IO.println("Launching missiles") >>
          IO.sleep(3.seconds) >>
          IO.println("Missiles launched, releasing lock")
      }

  def randomSleep: IO[Unit] =
    IO(scala.util.Random.nextInt(100)).flatMap { ms =>
      IO.sleep((ms + 700).millis)
    }.void

  def p1: IO[Unit] =
    sem.permit.use(_ => IO.println("Running P1")) >> randomSleep

  def p2: IO[Unit] =
    sem.permit.use(_ => IO.println("Running P2")) >> randomSleep

  def run: IO[Unit] =
    Supervisor[IO].use { s =>
      s.supervise(launchMissiles) *>
        s.supervise(p1.foreverM).void *>
        s.supervise(p2.foreverM).void *>
        IO.sleep(5.seconds).void
    }

}
```

Initializing (unsafely) the `Semaphore` fails with this error.

```scala
[info] running (fork) examples.state.LeakyState
[error] Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
[error] 	at scala.Predef$.require(Predef.scala:325)
[error] 	at cats.effect.unsafe.IORuntimeCompanionPlatform.installGlobal(IORuntimeCompanionPlatform.scala:67)
[error] 	at cats.effect.IOApp.main(IOApp.scala:58)
[error] 	at cats.effect.IOApp.main$(IOApp.scala:35)
[error] 	at examples.state.LeakyState$.main(LeakyState.scala:9)
[error] 	at examples.state.LeakyState.main(LeakyState.scala)
```

Even when setting `Compile / run / fork := true` in `build.sbt`.

The workaround is to make it a `lazy val` together with forking enabled in `sbt`. So this does not work in Scastie: https://scastie.scala-lang.org/v7S7tnCsQ9yAL9gMSnxyhw

Since this example showcases exactly what users should not do, I don't expect a fix but raising the issue in case this could be a legit bug when interoping with side-effectful frameworks, e.g. initializing an `ActorSystem` within `IOApp`.

### PR DESCRIPTION
**Pull request by djspiewak**
Fixes #1918 

When the global runtime is *already* initialized by the time `main` runs, we now treat this as a warning (which prints to stderr) rather than a fatal error (which is what we did previously). The warning is still important because the user really needs to know that we're ignoring their custom configurations.

We can probably do better than the text on this warning and give the user some actionable steps to track down *why* the warning is appearing.

### CODE REVIEW

File: core/js/src/main/scala/cats/effect/IOApp.scala [hunk 1]
```diff
@@ -198,6 +198,13 @@ trait IOApp {
           runtimeConfig)
       }
 
+      if (!installed) {
+        System
+          .err
+          .println(
+            "WARNING: Cats Effect global runtime already initialized; custom configurations will be ignored")
```
Comment (vasilmkd) [inline core/js/src/main/scala/cats/effect/IOApp.scala:205]: Should we do the fancy yellow colored [text](https://www.scala-lang.org/api/2.13.6/scala/Console$.html#YELLOW:String(%22\u001B[33m%22))?

**Review by vasilmkd — COMMENTED** [review]
Bummer, it looks like you forgot the mima filters.

File: core/js/src/main/scala/cats/effect/IOApp.scala (hunk 1 above)
Comment (djspiewak) [reply core/js/src/main/scala/cats/effect/IOApp.scala:205]: We could! It generally looks terrible in log output though. Am open to bikeshedding on this one.

Comment (vasilmkd) [reply core/js/src/main/scala/cats/effect/IOApp.scala:205]: I agree with function over form in this case.

**Review by vasilmkd — APPROVED** [review]
