### PR TITLE
Fixed several extremely rare race conditions in runloop resumption

### LINKED ISSUE #1816: Cancelation deadlock in `IO.race`
Just as soon as #1814 was merged, the `AsyncBenchmark.race` benchmark is deadlocking. We had this exact same issue when we had a specialized implementation of `RacePair` and `Race`. Last time we chalked it up to a bad implementation of the specialized `Race` combinator, but now I'm suspecting that something fundamental is buggy in IO.

The only idea I can think of is that somehow fibers which are started but canceled before they've had the chance to run don't propagate their `Canceled` outcome to the outside world. If we look at the fix from today:
```scala
back <- onCancel(
  poll(result.get), {
    for {
      doneA <- deferred[Unit]
      doneB <- deferred[Unit]
      _ <- start(guarantee(fibA.cancel, doneA.complete(()).void)) // <- the guarantee is never called with an `Outcome`
      _ <- start(guarantee(fibB.cancel, doneB.complete(()).void)) // <- or here
      _ <- doneA.get
      _ <- doneB.get
    } yield ()
  }
)
```

I'm sorry if my intuition is wrong.

Wild speculation at 3:30 AM and I hope I'm wrong. What if the finalizer in guarantee is never even registered as a finalizer?

### PR DESCRIPTION
**Pull request by djspiewak**
Fixes #1816 

There's a lot in here, review carefully. All the credit goes to @vasilmkd and @RaasAhsan.

### CODE REVIEW

File: kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala [hunk 1]
```diff
@@ -104,41 +104,25 @@ trait GenConcurrent[F[_], E] extends GenSpawn[F, E] {
...
+            canA <- start(fibA.cancel)
+            canB <- start(fibB.cancel)
+
+            _ <- canA.join
+            _ <- canB.join
+          } yield ())
+      } yield back match {
+        case Left(oc) => Left((oc, fibB))
+        case Right(oc) => Right((fibA, oc))
+      }
```
Comment (vasilmkd) [inline kernel/shared/src/main/scala/cats/effect/kernel/GenConcurrent.scala:125]: So much faster-er and lighter-weight-er-er.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 2]
```diff
@@ -663,7 +663,7 @@ private final class IOFiber[A](
             state.compareAndSet(ContStateWaiting, ContStateInitial)
             ()
           }
-          finalizers.push(EvalOn(fin, currentCtx))
+          finalizers.push(fin)
```
Comment (vasilmkd) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:671]: Really nice.

**Comment by vasilmkd** [comment]
Doing another pass.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 3]
```diff
@@ -567,7 +567,7 @@ private final class IOFiber[A](
                 // `wasFinalizing` is published
                 if (finalizing == state.wasFinalizing) {
                   if (!shouldFinalize()) {
```
Comment (vasilmkd) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:569]: Just to confirm, `ContState` guards against very late, repeated async invocations, while if `ContState` itself is not completed, the fiber can't be, so the `outcome` check is not needed. Is my intuition correct?

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 4]
```diff
@@ -592,15 +592,20 @@ private final class IOFiber[A](
...
+                 * ownership of the runloop.
                  */
                 loop()
-              } /*
-               * If we are canceled, just die off and let `cancel` or `get` win
-               * the race to `resume` and run the finalisers.
+              }
+
+              /*
+               * If we are canceled or completed or in hte process of finalizing
```
Comment (vasilmkd) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:606]: Nitpicking: the instead of hte, and two lines below, finalizers instead of finalisers.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 5]
```diff
@@ -703,7 +708,10 @@ private final class IOFiber[A](
                * finalisers.
                */
               if (resume()) {
-                asyncCancel(null)
+                if (shouldFinalize())
+                  asyncCancel(null)
+                else
+                  suspend()
```
Comment (vasilmkd) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:714]: Critical fix right here. So glad we found this.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 6]
```diff
@@ -741,7 +749,7 @@ private final class IOFiber[A](
               }
 
               runLoop(next, nextIteration)
-            } else {
+            } else if (outcome == null) {
```
Comment (vasilmkd) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:752]: Question for future development. Is there any chance `outcome` can be non-volatile and published in terms of `suspended`?

Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:752]: I'm guessing no because of the interaction with `CallbackStack`.

**Comment by vasilmkd** [comment]
Running the fix on my machine for some time.

**Comment by vasilmkd** [comment]
Running 3 forks of the fix in parallel.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 3 above)
Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:569]: Also the fact that we set `suspended` to `false` in `done`, meaning that you can't `resume()` if `outcome` is non-null.

**Review by vasilmkd — APPROVED** [review]
2 hours running this, with 3 forks in parallel. I'm calling it a success. Monumental effort, I'm absolutely grateful for your time. @RaasAhsan @djspiewak

**Comment by kubukoz** [comment]
I will remember the moment I saw this merge till the day I die.
