### PR TITLE
Catch stray exceptions in `uncancelable` body

### LINKED ISSUE #3609: error in bracket finalizer can stop fiber from progressing.
Consider this example:
```scala
//> using lib "org.typelevel::cats-effect::3.4.10"

import cats.effect.IOApp
import cats.effect.IO

object ExampleCE3 extends IOApp.Simple {

  def run: IO[Unit] =
    actionThatHangs

  // fails with
  // java.lang.RuntimeException
  def actionThatFails =
    IO.unit.bracket(_ => IO.unit)(_ => IO.raiseError(new RuntimeException))

  // fails with 
  // java.lang.NullPointerException: Cannot invoke "cats.effect.IO.as(Object)" because the return value of "scala.Function1.apply(Object)" is null
  def actionThatFailsWithNPE =
    IO.unit.bracket(_ => IO.unit)(_ => (null: IO[Unit]))

  // some stacktrace is printed
  // java.lang.NullPointerException: Cannot invoke "cats.effect.IO.void()" because "null" is null
  // But the program doesn't terminate
  // Also, it can't be killed with "ctrl-c"
  def actionThatHangs =
    IO.unit.bracket(_ => IO.unit)(_ => (null: IO[Unit]).void)
}
```

Run it with `scala-cli ExampleCE3.scala`

This is the first fiber dump, acquired with `kill -USR1 <PID>`
```
cats.effect.IOFiber@7b2ec5f5 WAITING
 
cats.effect.IOFiber@5e326b4b ACTIVE
 ├ bracket @ ExampleCE3$.actionThatHangs(ExampleCE3.scala:26)
 ├ run$ @ ExampleCE3$.run(ExampleCE3.scala:6)
 ├ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 ├ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 ╰ bracket @ ExampleCE3$.actionThatHangs(ExampleCE3.scala:26)
 ```

This is the fiber dump after `ctrl-c`
```
cats.effect.IOFiber@7ab712ce WAITING
 ├ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 ╰ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 
cats.effect.IOFiber@7b2ec5f5 WAITING
 
cats.effect.IOFiber@5e326b4b ACTIVE
 ├ bracket @ ExampleCE3$.actionThatHangs(ExampleCE3.scala:26)
 ├ run$ @ ExampleCE3$.run(ExampleCE3.scala:6)
 ├ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 ├ main$ @ ExampleCE3$.main(ExampleCE3.scala:6)
 ╰ bracket @ ExampleCE3$.actionThatHangs(ExampleCE3.scala:26)
 ```

### PR DESCRIPTION
**Pull request by armanbilge**
Fixes https://github.com/typelevel/cats-effect/issues/3609.

### CODE REVIEW

**Review by djspiewak — APPROVED** [review]
Aww nuts. That's a silly miss.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 1]
```diff
@@ -530,12 +530,21 @@ private final class IOFiber[A](
...
+                onFatalFailure(t)
+            }
+
           /*
            * The uncancelableK marker is used by `succeeded` and `failed`
            * to unmask once body completes.
            */
           conts = ByteStack.push(conts, UncancelableK)
-          runLoop(cur.body(poll), nextCancelation, nextAutoCede)
+          runLoop(next, nextCancelation, nextAutoCede)
```
Comment (armanbilge) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala:547]: Wait, is this a mistake? if the `try` fails we probably shouldn't be pushing onto the conts stack?

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala:547]: Oh… yes. Let me see if I can contrive a failing test here…
