### PR TITLE
Avoid Throwable#addSuppressed & CompositeException

### LINKED ISSUE #452: Reconsider Throwable addSuppressed usage
See https://github.com/typelevel/cats-effect/pull/449 for an initial proposal and the exchange of thoughts and ideas around it.

### PR DESCRIPTION
**Pull request by dwijnand**
Log as a last resort.

Fixes #452

### CODE REVIEW

**Comment by dwijnand** [comment]
In the interests of not logging exceptions in tests I tried to implement `ReleaseRecover#recover` with a new `RaiseErrors` constructor for `IO`, but I got stuck uncertain where between `IOPlatform.unsafeResync`, `IORunLoop.step`, and `IORunLoop.loop` I needed to make the changes, so I just left it as a TODO for someone else.

Let me know if there's anything I can do that would help to approve this.

File: laws/shared/src/test/scala/cats/effect/IOTests.scala [hunk 1]
```diff
@@ -652,6 +652,42 @@ class IOTests extends BaseTestsSuite {
...
+  test("bracket signals the error in use and logs the error from release") {
+    val e1 = new RuntimeException("error in use")
+    val e2 = new RuntimeException("error in release: expected to be logged during test")
+
+    val r = IO.unit.bracket(_ => IO.raiseError(e1))(_ => IO.raiseError(e2))
+      .attempt
+      .unsafeRunSync()
+
+    r shouldEqual Left(e1)
+    // TODO: assert e2 is logged
```
Comment (alexandru) [inline laws/shared/src/test/scala/cats/effect/IOTests.scala]: You can test this in two ways:

1. override `System.err`, like here: https://github.com/typelevel/cats-effect/blob/v1.1.0/core/shared/src/test/scala/cats/effect/internals/TestUtils.scala#L55 (this should work with Scala.js too)
2. execute that logic on top of a thread with your own [UncaughtExceptionHandler](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.UncaughtExceptionHandler.html), this only works on the JVM

File: core/shared/src/test/scala/cats/effect/internals/TestUtils.scala [hunk 2]
```diff
@@ -52,9 +53,17 @@ trait TestUtils {
   /**
    * Catches `System.err` output, for testing purposes.
    */
-  def catchSystemErr(thunk: => Unit): String = synchronized {
-    val oldErr = System.err
+  def catchSystemErr(thunk: => Unit): String = {
     val outStream = new ByteArrayOutputStream()
+    catchSystemErrInto(outStream)(thunk)
+    outStream.toString("utf-8")
```
Comment (rossabaker) [inline core/shared/src/test/scala/cats/effect/internals/TestUtils.scala]: Nit: I usually refer to `StandardCharsets.UTF_8` just to have a constant, but I won't hold up progress over it.
