### PR TITLE
Fix #108: re-throw exception in IO.async after callback was called once

### LINKED ISSUE #108: Exception silently ignored in async after callback
I'm not sure if this is a bug, but it's surprising:
```scala
scala> val tsk = cats.effect.IO.async[Int] { cb => cb(Right(42)); throw new Exception }
tsk: cats.effect.IO[Int] = IO$830563880

scala> tsk.unsafeRunSync()
res1: Int = 42
```
It's probably due to [this line](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/IO.scala#L427): the callback would be called twice in this case, but the second one (with the exception) is ignored (correctly) due to the `onceOnly`.

### PR DESCRIPTION
**Pull request by alexandru**
Fixes #108 by re-throwing thrown exceptions in `IO.async` after the callback was called once.

As I said in [my comment](https://github.com/typelevel/cats-effect/issues/108#issuecomment-355314764):

`IO.async` represents an async communication protocol between a producer and a consumer and unhandled exceptions represent a **protocol violation**, at which point the behavior can be considered to be undefined.

We can agree however that swallowing exceptions with no error reporting is bad. But it's also not correct to do a `printStackTrace` because many web services will just throw $stderr into `/dev/null`, relying on logging libraries like [Logback](https://logback.qos.ch/) to report any errors that happen.

And because `cats.effect.IO` does not have an underlying `Scheduler` or `ExecutionContext` that can report errors in such instances, the only sensible thing to do is to re-throw the error.

Re-throwing the error will either blow the main application thread, or the thread of a thread-pool that has exception reporting in place. With a sane thread-pool implementation and configuration (N.B. not all of them are sane), you can then get error reporting for unhandled errors.

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala [hunk 1]
```diff
@@ -69,10 +69,18 @@ private[effect] object IOPlatform {
...
-  def onceOnly[A](f: A => Unit): A => Unit = {
+  def onceOnly[A](f: Either[Throwable, A] => Unit): Either[Throwable, A] => Unit = {
     val wasCalled = new AtomicBoolean(false)
 
-    a => if (wasCalled.getAndSet(true)) () else f(a)
+    a => if (wasCalled.getAndSet(true)) {
+      // Re-throwing error in case we can't signal it
+      a match {
+        case Left(err) => throw err
+        case Right(_) => ()
```
Comment (LukaJCB) [inline core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: Seems this is currently not being hit?

Comment (alexandru) [reply core/jvm/src/main/scala/cats/effect/internals/IOPlatform.scala]: It should be, at least in `OnceOnlyTests`.

**Comment by johnynek** [comment]
I didn't see an explicit test of the case we are trying to fix here (someone violating the protocol, yet us not silently eating the exception).

Can we test that case directly, or did I miss it?

**Comment by alexandru** [comment]
@johnynek should be at https://github.com/typelevel/cats-effect/pull/111/files#diff-a574b3ecff97cad1f426b4438320fc89R54

**Comment by johnynek** [comment]
@alexandru yes indeed. Sorry I missed it.

This looks good to me.
