### PR TITLE
Fix #316: fix IO.bracket to be stack safe; add laws to SyncLaws

### LINKED ISSUE #316: [1.0.0-RC3] StackOverflowError
I've upgraded to RC3, and my program (a long process on more than 1M files) now fail very quickly with :
```
java.lang.StackOverflowError
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:137)
    at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:134)
    at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
    at cats.effect.internals.IOBracket$.$anonfun$apply$2(IOBracket.scala:46)
    at cats.effect.internals.IOBracket$.$anonfun$apply$2$adapted(IOBracket.scala:35)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:134)
    at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
    at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:35)
    at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:32)
    at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:328)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:117)
    at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
    at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:134)
    ...
```

I use only 2 `bracket()` (with `better.files` API, and `F[_] : Sync` executed with `IO`):
```
  private def writeGz(s: String, f: File): F[Unit] =
    F.bracket(F.delay(f.createIfNotExists(createParents = true).newOutputStream.asGzipOutputStream()))(out => F.delay(out.write(s.getBytes)).void)(out => F.delay(out.close()))

  private def readGZ(f: File): F[List[String]] =
    F.bracket(F.delay(f.newInputStream.asGzipInputStream()))(is => F.delay(is.lines.toList))(is => F.delay(is.close()))
```

I also use lot of `F.delay()`, some `Timer.sleep()` and some `F.raiseError()`.

I will try to extract a minimal failing case later...

### PR DESCRIPTION
**Pull request by alexandru**
Fixes #316

### CODE REVIEW

File: laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala [hunk 1]
```diff
@@ -102,13 +102,41 @@ trait SyncLaws[F[_]] extends BracketLaws[F, Throwable] with DeferLaws[F] {
...
+      F.bracket(F.unit)(F.pure(_))(_ => F.unit).flatMap(_ => acc)
+    }
+    result <-> F.pure(())
+  }
+
+  def stackSafetyOfGuaranteeOnRepeatedLeftBinds(iterations: Int) = {
+    val result = (0 until iterations).foldRight(F.delay(())) { (_, acc) =>
+      acc.flatMap(_ => F.guarantee(F.unit)(F.unit))
+    }
+    result <-> F.pure(())
```
Comment (LukaJCB) [inline laws/shared/src/main/scala/cats/effect/laws/SyncLaws.scala]: We should've added these earlier 👍
