### PR TITLE
Exit on fatal error

### LINKED ISSUE #1298: Make the blocking pool private within IORuntime
We want to leave the door open to, in the future, not use a thread pool.

### LINKED ISSUE #1327: Work stealing thread pool not parking
I was running a test application today in SBT where it doesn't fork the JVM. I noticed that after the application terminated, the SBT process was seeing 800% CPU utilization. I captured a thread dump and saw:
```
"io-compute-1" #197 daemon prio=5 os_prio=31 tid=0x00007feae741b800 nid=0x13d03 runnable [0x000070000fef4000]
   java.lang.Thread.State: RUNNABLE
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c7322960> (a cats.effect.unsafe.WorkStealingThreadPool)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at cats.effect.unsafe.WorkerThread.park(WorkerThread.scala:166)
        at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:268)

   Locked ownable synchronizers:
        - None
```
It seems like threads these threads are actually executing and _not_ parking, which is causing the high CPU. Compare with a regular executor:
```

"pool-17-thread-12" #188 prio=5 os_prio=31 tid=0x00007f9e72278000 nid=0xb803 waiting on condition [0x0000700010aa5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c6c59170> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### LINKED ISSUE #1355: What to do when fatal errors are thrown
The `IOFiber` runloop currently handles `NonFatal` exceptions.

Any exception not caught by this method continues down the call stack in the carrier thread loop. For example, in the work stealing pool, these are currently not handled, the carrier thread crashes and the application continues with 1 fewer threads (we currently do not have a mechanism of reporting this fatal error to the place where `unsafeRunSync()` was called, so no shutdown and vm exit logic can occur).

If you thought this is somehow better managed by the old Java fixed thread pool, you would be wrong. Running the following application inside sbt with a fixed IO compute thread pool completely hangs the process.

```scala
object App extends IOApp.Simple {
  def run: IO[Unit] = IO[Unit](throw new OutOfMemoryError("Boom!"))
}
```

None of this is ideal, as you can imagine. We need to arrive at an acceptable solution. Keep in mind that we should keep the experience somewhat consistent between our work stealing thread pool which we completely control and can add new functionality to, compared to a java executor or a custom `ExecutionContext`.

Interestingly, this is somewhat at odds with the final decision made in https://github.com/typelevel/cats-effect/pull/1277.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #1327.
Resolves #1355.
Resolves #1298.

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala [hunk 1]
```diff
@@ -135,7 +135,14 @@ private final class WorkerThread(
     // Announce that this thread is no longer searching for work, if that was the case before.
     transitionFromSearching()
     // Execute the fiber.
-    fiber.run()
+    try fiber.run()
+    catch {
+      // Handle fatal errors.
+      case t: Throwable =>
+        pool.reportFailure(t)
+        fiber.errorCb(Left(t))
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: Oh! This is much nicer than what I was thinking of. The problem though is that we may have multiple separate fiber chains running on the same pool. Specifically, if someone is doing `unsafeRunSync()` multiple times against the same `IORuntime`. I think I'm kind of okay with all-but-one of them deadlocking though.

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala [hunk 2]
```diff
@@ -135,7 +135,14 @@ private final class WorkerThread(
...
+        System.exit(1)
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: IMO we shouldn't exit. Let's allow the downstream callback to do that. However, we *should* completely shut down the pool.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 3]
```diff
@@ -67,8 +67,9 @@ private final class IOFiber[A](
     initMask: Int,
     cb: OutcomeIO[A] => Unit,
     startIO: IO[A],
-    startEC: ExecutionContext)
-    extends IOFiberPlatform[A]
+    startEC: ExecutionContext,
+    val errorCb: Left[Throwable, Nothing] => Unit
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: This is just `Throwable => Unit`. Also should be `private[effect] val`. This is actually pretty important because we can't really allocate reliably after an OOM.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 4]
```diff
@@ -222,7 +222,8 @@ sealed abstract class IO[+A] private () extends IOPlatform[A] {
       (oc: OutcomeIO[A]) =>
         oc.fold((), e => cb(Left(e)), ioa => cb(Right(ioa.asInstanceOf[IO.Pure[A]].value))),
       this,
-      runtime.compute
+      runtime.compute,
+      cb
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IO.scala]: The wrapping in `Left` should be here, IMO, and in some cases (e.g. `unsafeRunSync()`) we can avoid it altogether by slightly revising the signature of `unsafeRunFiber` (to take a `Throwable => Unit` and an `A => Unit` instead of a single one with `Either`).

**Review by djspiewak — CHANGES_REQUESTED** [review]

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala [hunk 5]
```diff
@@ -135,7 +135,14 @@ private final class WorkerThread(
     // Announce that this thread is no longer searching for work, if that was the case before.
     transitionFromSearching()
     // Execute the fiber.
-    fiber.run()
+    try fiber.run()
+    catch {
+      // Handle fatal errors.
+      case t: Throwable =>
```
Comment (RaasAhsan) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: This is catching all throwables (rather than just fatal `Error`s); is there another `try`/`catch` inside `fiber.run()` that catches nonfatal exceptions?

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 3 above)
Comment (RaasAhsan) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Eventually it's going to be lifted into a `Left` anyways though, since that's the signature of `cb`. It seems kind of futile to catch these fatal errors :P

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala (hunk 2 above)
Comment (RaasAhsan) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: What are the behaviors of the default `Executors` with respect to fatal errors? I'm a bit in favor of keeping consistent with that behavior unless there's a really good reason not to

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala (hunk 5 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: Yes, the `IOFiber` runloop catches non fatal errors.

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala (hunk 2 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: Downstream callback may not exit the VM, think about `unsafeRunSync()` from anywhere. You're right coupled with your previous comment about only one fiber chain being notified, this solution doesn't cut it.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 3 above)
Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: We must do _something_, currently a fatal error crashes a carrier thread from the work stealing thread pool and the program continues as if nothing happened. Feel free to try it.

Comment (djspiewak) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: > Eventually it's going to be lifted into a Left anyways though, since that's the signature of cb. It seems kind of futile to catch these fatal errors :P

Doesn't have to be. We can avoid the lifting for `unsafeRunSync` for example.

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala (hunk 5 above)
Comment (djspiewak) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: There also isn't a particularly clean "catch only fatal errors" mechanism, much less one I would trust when the VM is on fire because of one. Catching `Throwable` also has the advantage that we sweep up `InterruptedException`, which is currently incorrectly handled.

**Comment by vasilmkd** [comment]
Resolves #1327.
Resolves #1355.
Resolves #1298.

This is now basically a different PR, but I guess it could be useful to keep the old comments.

I have used the following `IOApp` for testing, let me know if the results are satisfying.
```scala
package cats.effect

import scala.concurrent.duration._

object CatsEffectApp extends IOApp.Simple {
  def run: IO[Unit] =
    for {
      _ <- IO.sleep(10.seconds)
      _ <- IO[Unit](throw new OutOfMemoryError("Boom!"))
    } yield ()
}
```

Console output:
Screen Shot 2020-10-25 at 02 10 22

JDK Mission Control screenshot during execution:
Screen Shot 2020-10-25 at 02 34 24

JDK Mission Control screenshot after execution:
Screen Shot 2020-10-25 at 02 34 49

Activity Monitor screenshot after execution (no spinning threads):
Screen Shot 2020-10-25 at 02 39 02

**Comment by vasilmkd** [comment]
I also apologize in advance for implementing another questionable concurrent data structure.

I know how much you dislike locking, but please keep in mind that we are trying to give best effort reporting to all ends of the world (think `unsafeRunSync()` locations) while the JVM is in a very bad state due to having thrown a fatal error. `unsafeRunSync()` operations are fairly rare in practice, so they don't need high performance concurrency.

On the other hand, we absolutely need this hand rolled hashtable because we are trying to signal fatal errors without further allocations.

Hopefully these reasons are enough to convince you.

**Comment by vasilmkd** [comment]
Special thanks to @djspiewak, I would not have been able to come close to this solution without your help.

**Comment by djspiewak** [comment]
> unsafeRunSync() operations are fairly rare in practice, so they don't need high performance concurrency.

Exactly this. I think locking is actually okay here.

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala [hunk 6]
```diff
@@ -315,7 +315,7 @@ private[effect] final class WorkStealingThreadPool(
       }
 
       // `unsafeRunFiber(true)` will enqueue the fiber, no need to do it manually
-      IO(runnable.run()).unsafeRunFiber(_.fold(reportFailure(_), _ => ()))(self)
+      IO(runnable.run()).unsafeRunFiber(reportFailure, _ => ())(self)
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala:318]: Amusingly, I completely forgot this was a source of unsafe running…

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 7]
```diff
@@ -211,18 +211,29 @@ sealed abstract class IO[+A] private () extends IOPlatform[A] {
...
 
-    val fiber = new IOFiber(
+    val fiber = new IOFiber[A](
       0,
-      (oc: OutcomeIO[A]) =>
-        oc.fold((), e => cb(Left(e)), ioa => cb(Right(ioa.asInstanceOf[IO.Pure[A]].value))),
+      oc =>
+        oc.fold(
+          (),
+          t => {
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Very minor nit: I generally prefer `{ t =>` rather than `t => {` (since the former syntax works with paren-less function calls while the latter syntax does not)

File: core/shared/src/main/scala/cats/effect/IOFiber.scala [hunk 8]
```diff
@@ -135,15 +135,33 @@ private final class IOFiber[A](
...
+          val len = runtime.fiberErrorCbs.hashtable.length
+          while (idx < len) {
+            val cb = runtime.fiberErrorCbs.hashtable(idx)
+            if (cb != null) {
+              cb(t)
+            }
+            idx += 1
+          }
+        }
+        runtime.internalShutdown()
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/IOFiber.scala]: I think we have to shut down the runtime *before* we notify the callbacks, otherwise one could sneak in as we're notifying.

File: core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala [hunk 9]
```diff
@@ -34,12 +34,14 @@ avoid unintentionally degrading your application performance.
 """)
 // Constructor visible in the effect package for use in benchmarks.
 final class IORuntime private[effect] (
-    val compute: ExecutionContext,
+    private[effect] val compute: ExecutionContext,
```
Comment (djspiewak) [inline core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala]: I think that @SystemFw wanted these to be public. `blocking` is the one that really needs to be private; technically the other two can be public without a problem, I think.

File: core/jvm/src/test/scala/cats/effect/IOAppSpec.scala [hunk 10]
```diff
@@ -142,4 +160,19 @@ package examples {
...
+    def run(args: List[String]): IO[ExitCode] =
+      IO(throw new OutOfMemoryError("Boom!")).as(ExitCode.Success)
+  }
+
+  object FatalErrorUnsafeRun extends IOApp {
+    import cats.effect.unsafe.implicits.global
+
+    def run(args: List[String]): IO[ExitCode] =
+      for {
+        _ <- IO(IO(throw new OutOfMemoryError("Boom!")).start.void.unsafeRunSync())
```
Comment (djspiewak) [inline core/jvm/src/test/scala/cats/effect/IOAppSpec.scala]: This test is probably more interesting if you add a few more lines like `_ <- IO(IO.never.unsafeRunSync()).start` to this for-comprehension.

File: core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala (hunk 9 above)
Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala]: Oh wow, I have made it exactly opposite to what's needed here https://github.com/typelevel/cats-effect/issues/1298, my bad...

File: core/shared/src/main/scala/cats/effect/IO.scala (hunk 7 above)
Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/IO.scala]: Unwanted syntax gone.

File: core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala (hunk 9 above)
Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/unsafe/IORuntime.scala]: Done.

File: core/jvm/src/test/scala/cats/effect/IOAppSpec.scala (hunk 10 above)
Comment (vasilmkd) [reply core/jvm/src/test/scala/cats/effect/IOAppSpec.scala]: Done.

File: core/shared/src/main/scala/cats/effect/IOFiber.scala (hunk 8 above)
Comment (vasilmkd) [reply core/shared/src/main/scala/cats/effect/IOFiber.scala]: Done. I made sure to handle interruption coming from the shutdown, hopefully this is how it should be done. Please check again.

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala [hunk 11]
```diff
@@ -339,8 +339,6 @@ private[effect] final class WorkStealingThreadPool(
     externalQueue.shutdown()
     // Send an interrupt signal to each of the worker threads.
     workerThreads.foreach(_.interrupt())
-    // Join all worker threads.
-    workerThreads.foreach(_.join())
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala:343]: Out of curiosity, what are the implications of removing this joining?

**Review by djspiewak — APPROVED** [review]

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala (hunk 11 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala:343]: If attempted from inside the pool, from a worker thread, it will try to join itself and deadlock.
