### PR TITLE
Use `IOApp#reportFailure` instead of `printStackTrace()` for blocking EC

### LINKED ISSUE #3993: Allow overriding how fatal errors are printed
The handling of some uncaught fatal errors can be customized by overriding `cats.effect.IOApp.reportFailure`.

However, such customization is currently not possible in many cases (all usages of `java.lang.Throwable.printStackTrace()`, for example [here](https://github.com/typelevel/cats-effect/pull/3008)).

Would it be possible to handle similar situations like in the fs2 reactive-streams integration [here](https://github.com/typelevel/fs2/blob/08cb8d41738833d2a5fa327eeed071f2bc19daa4/reactive-streams/src/main/scala/fs2/interop/reactivestreams/StreamSubscriber.scala#L147) i.e., by using (if defined) java thread's default `UncaughtExceptionHandler`?

This would allow one to redirect uncaught errors to a custom logger, so that it gets properly ingested in a logging stack/system.

### PR DESCRIPTION
**Pull request by fredfp**
fixes #3993

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala [hunk 1]
```diff
@@ -174,7 +174,7 @@ private[unsafe] abstract class IORuntimeCompanionPlatform { this: IORuntime.type
       threadPrefix,
       blockerThreadPrefix,
       60.seconds,
-      _.printStackTrace(),
+      self.compute.reportFailure,
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala]: I'm suspicious if this does the right thing. It might need to be written as `ex => self.compute.reportFailure(ex)`.

**Review by armanbilge — COMMENTED** [review]
Thanks for the PR! We can probably target this at `series/3.5.x` so it can be released sooner than later :)

**Comment by fredfp** [comment]
> Thanks for the PR! We can probably target this at `series/3.5.x` so it can be released sooner than later :)

That would be great, is there anything I could/should do about it?

**Comment by armanbilge** [comment]
Yes, you can rebase your branch and retarget the PR on GitHub.

**Comment by fredfp** [comment]
I'm not sure how to handle bincompat, I've pushed a 2nd commit with an attempt to address it.

File: core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala [hunk 2]
```diff
@@ -150,16 +154,24 @@ private[unsafe] abstract class IORuntimeCompanionPlatform { this: IORuntime.type
...
   def createDefaultBlockingExecutionContext(
-      threadPrefix: String = "io-blocking"): (ExecutionContext, () => Unit) = {
+      threadPrefix: String
+  ): (ExecutionContext, () => Unit) =
+    createDefaultBlockingExecutionContext(threadPrefix, _.printStackTrace())
+
+  def createDefaultBlockingExecutionContext(
+      threadPrefix: String = "io-blocking",
+      reportFailure: Throwable => Unit = _.printStackTrace()
+  ): (ExecutionContext, () => Unit) = {
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala]: Oops, I'm sorry. I missed that you added a new public API. We can't add new APIs or deprecate existing APIs in the 3.5.x line. That would force this PR to go to 3.x.

However, I still think these changes are good for 3.5.x and we can accomplish them without changing the public API. To do so, we can make this new method `private[effect]` and keep the existing public method un-deprecated. Then we can do the publication/deprecation in 3.x. Thoughts?

Comment (fredfp) [reply core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala]: It's done for 3.5.x, should I ignore the residual mima failures as they are not related to public apis?

File: std/shared/src/main/scala/cats/effect/std/Dispatcher.scala [hunk 3]
```diff
@@ -88,22 +87,21 @@ trait Dispatcher[F[_]] extends DispatcherPlatform[F] {
...
-    t.printStackTrace()
+  protected def reportFailure(t: Throwable): Unit
 
   // package-private because it's just an internal utility which supports specific implementations
   // anyone who needs this type of thing should use unsafeToFuture and then onComplete
   private[std] def unsafeRunAsync[A](fa: F[A])(cb: Either[Throwable, A] => Unit): Unit =
     unsafeToFuture(fa).onComplete(t => cb(t.toEither))(parasiticEC)
-}
-
-object Dispatcher {
```
Comment (armanbilge) [inline std/shared/src/main/scala/cats/effect/std/Dispatcher.scala]: You cannot make these changes compatibly. However, I don't think this particular change is important anyway. The `parasiticEC` is used in a very specific place to invoke a callback that we control i.e. a callback that should never fail. So I don't expect this `reportFailure` method to ever be invoked.

Comment (fredfp) [reply std/shared/src/main/scala/cats/effect/std/Dispatcher.scala]: Ok, removed for 3.5.x. I'll keep those on the side for 3.x.

Comment (armanbilge) [reply std/shared/src/main/scala/cats/effect/std/Dispatcher.scala]: Sorry, it's not compatible for 3.5.x or 3.x. Is there a situation where you think it is important?

Comment (fredfp) [reply std/shared/src/main/scala/cats/effect/std/Dispatcher.scala]: I agree, I found them looking for instances of `printStackTrace` and tried to remove them, but those can stay as no user code should ever get executed on the parasiticEC.

File: core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala [hunk 4]
```diff
@@ -141,7 +141,11 @@ private[unsafe] abstract class IORuntimeCompanionPlatform { this: IORuntime.type
       threadPrefix: String = "io-compute",
       blockerThreadPrefix: String = DefaultBlockerPrefix)
       : (WorkStealingThreadPool, () => Unit) =
-    createWorkStealingComputeThreadPool(threads, threadPrefix, blockerThreadPrefix)
+    createWorkStealingComputeThreadPool(
+      threads,
+      threadPrefix,
+      blockerThreadPrefix,
+      reportFailure = t => self.compute.reportFailure(t))
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala]: Hang on, sorry. I'm just a little bit confused by this. Does this actually work?

Here's why I'm confused: this method is building the `WorkStealingComputeThreadPool` which will be installed as `compute` in `self.compute`. Thus we are implementing `reportFailure` of this `ExecutionContext` by delegating recursively to itself. Is that right or am I mixed up somehow?

Comment (fredfp) [reply core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala]: You are absolutely right, thanks for spotting this. I went to check pre-3.4 source code and `cats.effect.IOApp#reportFailure` didn't exist at the time, so I reverted to the previous behaviour which is the best we can do.

File: core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala [hunk 5]
```diff
@@ -151,15 +151,22 @@ private[unsafe] abstract class IORuntimeCompanionPlatform { this: IORuntime.type
     createDefaultComputeThreadPool(self(), threads, threadPrefix)
 
   def createDefaultBlockingExecutionContext(
-      threadPrefix: String = "io-blocking"): (ExecutionContext, () => Unit) = {
+      threadPrefix: String = "io-blocking"
+  ): (ExecutionContext, () => Unit) =
+    createDefaultBlockingExecutionContext(threadPrefix, _.printStackTrace())
+
+  private[effect] def createDefaultBlockingExecutionContext(
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala:158]: We should create a follow-up to make this public in 3.x.

File: core/shared/src/main/scala/cats/effect/IO.scala [hunk 6]
```diff
@@ -899,7 +899,7 @@ sealed abstract class IO[+A] private () extends IOPlatform[A] {
       cb(Left(new CancellationException("The fiber was canceled"))),
       t => {
         if (!NonFatal(t)) {
-          t.printStackTrace()
+          runtime.compute.reportFailure(t)
```
Comment (armanbilge) [inline core/shared/src/main/scala/cats/effect/IO.scala]: Hmm, I'm look at this and suddenly I'm not so sure about this change. Here's the problem.

`!NonFatal(t)` "not non-fatal" i.e. it _is_ a fatal error. When there is a fatal error (e.g. `OutOfMemoryError`) the JVM is in an inconsistent state and we cannot assume that it is safe to allocate.

The `runtime.compute.reportFailure(t)` may involve allocating an `IO`/`Fiber` and therefore is not safe to do in general.

Meanwhile `t.printStackTrace()` is know to be always safe.

**Review by armanbilge — APPROVED** [review]

**Review by djspiewak — APPROVED** [review]
