### PR TITLE
Fix a few Supervisor bugs

### LINKED ISSUE #3394: Closed `Supervisor` strangeness
It seems, that a closed (finalized) `Supervisor` happily starts fibers, and never cancels/joins them

```scala
import scala.concurrent.duration._

import cats.effect.{ IO, IOApp }
import cats.effect.std.Supervisor

object Sup extends IOApp.Simple {

  def run: IO[Unit] = {
    Supervisor[IO](await = false).use { sup =>
      sup.supervise(IO.println("started 1") *> IO.never.onCancel(IO.println("cancelled 1"))).as(sup)
    }.flatMap { sup =>
      sup.supervise(IO.println("started 2") *> IO.never.onCancel(IO.println("cancelled 2"))) *> (
        IO.sleep(1.second) *> IO.println("done")
      )
    }
  }
}
```

This prints:

```
started 1
cancelled 1
started 2
done
```

Oviously we shouldn't leak the `Supervisor` object, but still, this feels wrong...

### PR DESCRIPTION
**Pull request by durban**
This PR fixes a few bugs in `Supervisor` (and creates an unknown number of new ones ;-).

Fixed bugs (at least the ones I remember spotting; I tried to write tests for them, couldn't for all of them):

- #3394
- With `checkRestart`, `cancel` allowed and didn't wait for one last restart.
- `supervise`/close race (although, due to #3394, close wasn't effective anyway).
- With `checkRestart`, if `cancel` cancelled the working fiber before it did anything, the finalizer (which removes the fiber from the map) did not run. (This was effectively a memory leak.)

### CODE REVIEW

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala [hunk 1]
```diff
@@ -17,11 +17,17 @@
...
+import cats.syntax.all._
+
 import org.specs2.specification.core.Fragments
 
 import scala.concurrent.duration._
 
-class SupervisorSpec extends BaseSpec {
+class SupervisorSpec extends BaseSpec with DetectPlatform {
+
+  sequential
```
Comment (djspiewak) [inline tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Do we need this?

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala [hunk 2]
```diff
@@ -17,11 +17,17 @@
...
+
+  override def executionTimeout = 60.seconds
```
Comment (djspiewak) [inline tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Oooof. Can we lower iteration counts instead?

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala [hunk 3]
```diff
@@ -229,5 +235,68 @@ class SupervisorSpec extends BaseSpec {
...
+
+    def superviseFinalizeRace(mkSupervisor: Resource[IO, Supervisor[IO]], task: IO[Unit]) = {
+      val tsk = IO.uncancelable { poll =>
+        mkSupervisor.allocated.flatMap {
+          case (supervisor, close) =>
+            supervisor.supervise(IO.never[Unit]).replicateA(100).flatMap { fibers =>
+              val tryFork = supervisor.supervise(task).map(Some(_)).recover {
+                case ex: IllegalStateException
+                    if ex.getMessage == "supervisor already shutdown" =>
+                  None
```
Comment (djspiewak) [inline tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Might be a bit easier to diagnose an eventual failure here if we convert this into a side-effecting test assertion.

```suggestion
                case ex: IllegalStateException =>
                  ex.getMessage mustEqual "supervisor already shutdown"
                  None
```

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala [hunk 4]
```diff
@@ -229,5 +235,68 @@ class SupervisorSpec extends BaseSpec {
...
+    }
+
+    "restart / cancel race" in real {
+      val tsk = constructor(false, Some(_ => true)).use { supervisor =>
+        IO.ref(0).flatMap { counter =>
+          supervisor.supervise(counter.update(_ + 1) *> IO.canceled).flatMap { adaptedFiber =>
+            IO.sleep(100.millis) *> adaptedFiber.cancel *> adaptedFiber.join *> (
+              (counter.get, IO.sleep(100.millis) *> counter.get).flatMapN {
+                case (v1, v2) =>
+                  IO((v1: Int) mustEqual (v2: Int))
```
Comment (djspiewak) [inline tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Are the type ascriptions needed?

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala [hunk 5]
```diff
@@ -229,5 +235,68 @@ class SupervisorSpec extends BaseSpec {
...
+              }
+            )
+          }
+        }
+      }
+
+      tsk.parReplicateA_(if (isJVM) 10000 else 5).as(ok)
```
Comment (djspiewak) [inline tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Why do we need to replicate it at all on non-JVM platforms?

Also, I'm assuming this is the test that takes most of the time?

File: std/shared/src/main/scala/cats/effect/std/Supervisor.scala [hunk 6]
```diff
@@ -244,44 +317,60 @@ object Supervisor {
...
+
+        def add(token: Unique.Token, fiber: Fiber[F, Throwable, _]): F[Boolean] =
+          stateRef.modify {
+            case null => (null, false)
+            case map => (map.updated(token, fiber), true)
+          }
 
         private[this] val allFibers: F[List[Fiber[F, Throwable, _]]] =
-          stateRef.get.map(_.values.toList)
+          stateRef.getAndSet(null).map(_.values.toList)
```
Comment (djspiewak) [inline std/shared/src/main/scala/cats/effect/std/Supervisor.scala:342]: So `null` is the signal that we've decided to kill ourselves? Basically, the invariant here is that `joinAll`/`cancelAll` can only be called at the end of the world, when the `Supervisor` is shutting down. Can we toss that in a comment so we don't forget it?

**Review by djspiewak — CHANGES_REQUESTED** [review]
Ouch this is hairy. Nice work. :) Some minor nits.

**Comment by djspiewak** [comment]
Also it occurs to me that, with this, we might not need the double-check on closure state in #3923

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala (hunk 1 above)
Comment (durban) [reply tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: With lowering the iteration counts, I think we will be able to avoid this.

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala (hunk 4 above)
Comment (durban) [reply tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Nope, I don't even remember why I did those :slightly_smiling_face:

File: tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala (hunk 5 above)
Comment (durban) [reply tests/shared/src/test/scala/cats/effect/std/SupervisorSpec.scala]: Good point; I think I copied the `if (isJVM) ... else 5` part from somewhere.

For me, it was usually `supervise / finalize race with checkRestart` that timed out.

File: std/shared/src/main/scala/cats/effect/std/Supervisor.scala (hunk 6 above)
Comment (durban) [reply std/shared/src/main/scala/cats/effect/std/Supervisor.scala:342]: There is already a comment in `abstract class State` about `joinAll`/`cancelAll`, but I'll note it here too.

**Comment by durban** [comment]
FTR there was a `Dispatcher` failure (https://github.com/typelevel/cats-effect/actions/runs/7678308491/job/20928046255#step:24:4779), but seemed unrelated to this PR, so I just restarted the CI jobs.

**Review by djspiewak — APPROVED** [review]
Awesome!
