### PR TITLE
Resolved issue with fatal errors being eaten

### LINKED ISSUE #2927: `IO` swallows fatal errors on JS
First reported in https://github.com/disneystreaming/weaver-test/issues/503.

```scala
//> using scala "3.1.1"
//> using platform "scala-js"
//> using jsVersion "1.9.0"
//> using lib "org.typelevel::cats-effect::3.3.9"

import cats.effect._
import cats.effect.unsafe.implicits._

object Main {
  def main(args: Array[String]): Unit = {
    val io = IO(throw new VirtualMachineError {}).attempt.flatMap(IO.println) <* IO.println("BOOM")
    io.unsafeToFuture()
  }
}
```

```
Right(null)
BOOM
/tmp/main12791209756503579234.js:11013
    throw $ct_jl_IllegalStateException__T__(new $c_jl_IllegalStateException(), "Promise already completed.")
    ^

<ref *1> java.lang.IllegalStateException: Promise already completed.
    at $f_s_concurrent_Promise__complete__s_util_Try__s_concurrent_Promise (/tmp/main12791209756503579234.js:11013:45)
    at $c_s_concurrent_impl_Promise$DefaultPromise.complete__s_util_Try__s_concurrent_Promise (/tmp/main12791209756503579234.js:39414:10)
    at $f_s_concurrent_Promise__success__O__s_concurrent_Promise (/tmp/main12791209756503579234.js:11017:16)
    at $c_s_concurrent_impl_Promise$DefaultPromise.success__O__s_concurrent_Promise (/tmp/main12791209756503579234.js:39417:10)
    at $ps_Lcats_effect_IO__$anonfun$12__s_concurrent_Promise__O__V (/tmp/main12791209756503579234.js:13760:7)
    at $ps_Lcats_effect_IO__$anonfun$adapted$3__s_concurrent_Promise__O__O (/tmp/main12791209756503579234.js:13763:3)
    at /tmp/main12791209756503579234.js:13844:432
    at $c_sjsr_AnonFunction1.apply__O__O (/tmp/main12791209756503579234.js:23475:43)
    at $ps_Lcats_effect_IO__$anonfun$17$$anonfun$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__V (/tmp/main12791209756503579234.js:13784:13)
    at $ps_Lcats_effect_IO__$anonfun$18$$anonfun$adapted$3__F1__F1__Lcats_effect_unsafe_IORuntime__Lcats_effect_IO__O (/tmp/main12791209756503579234.js:13787:3) {
  jl_Throwable__f_s: 'Promise already completed.',
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: [Circular *1],
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null
}
```

Interestingly, this _doesn't_ happen when using `IOApp`.

```scala
object Main extends IOApp.Simple {
  def run = IO(throw new VirtualMachineError {}).attempt.flatMap(IO.println) <* IO.println("BOOM")
}
```

```
Main$$anon$1
  at Main$.run$$anonfun$1(/tmp/main650896950790062058.js:19523:9)
  at {anonymous}()(/tmp/main650896950790062058.js:19562:5)
  at scala.scalajs.runtime.AnonFunction0.apply(/tmp/main650896950790062058.js:24034:43)
  at cats.effect.IOFiber.runLoop(/tmp/main650896950790062058.js:36329:52)
  at cats.effect.IOFiber.execR(/tmp/main650896950790062058.js:37150:5)
  at cats.effect.IOFiber.run(/tmp/main650896950790062058.js:37592:7)
  at cats.effect.unsafe.FiberAwareExecutionContext.cats$effect$unsafe$FiberAwareExecutionContext$$_$execute$$anonfun$1(/tmp/main650896950790062058.js:14367:7)
  at cats.effect.unsafe.FiberAwareExecutionContext$$anon$1.run(/tmp/main650896950790062058.js:14405:73)
  at org.scalajs.macrotaskexecutor.MacrotaskExecutor$.execute$$anonfun$1(/tmp/main650896950790062058.js:26909:14)
  at org.scalajs.macrotaskexecutor.MacrotaskExecutor$.execute$$anonfun$adapted$1(/tmp/main650896950790062058.js:26912:3)
```

### PR DESCRIPTION
**Pull request by djspiewak**
In theory, this *probably* affected the JVM in some way as well, but it's hard to say since interrupt points are sufficiently frequent that it appears to have been masked.

Fixes #2927

### CODE REVIEW

File: tests/js/src/main/scala/catseffect/examplesplatform.scala [hunk 1]
```diff
@@ -53,7 +57,7 @@ package examples {
         // emulates the situation in browsers
         js.Dynamic.global.process.exit = js.undefined
       args.shift()
-      apps(app).main(Array.empty)
+      apps.get(app).map(_.main(Array.empty)).orElse(rawApps.get(app).map(_.main(Array.empty)))
```
Comment (armanbilge) [inline tests/js/src/main/scala/catseffect/examplesplatform.scala]: We might want to toss a `.get` on the end of this so it throws an exception if it can't find the app (i.e. we forget to register it properly :)

**Review by armanbilge — APPROVED** [review]
