### PR TITLE
Setup `UncaughtExceptionHandler` for `WorkerThread`

### LINKED ISSUE #4232: Configure `UncaughtExceptionHandler` for `WorkerThread`s

### PR DESCRIPTION
**Pull request by armanbilge**
Closes https://github.com/typelevel/cats-effect/issues/4232.

### CODE REVIEW

**Comment by djspiewak** [comment]
`prePR` time

File: core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala [hunk 1]
```diff
@@ -79,8 +79,10 @@ private[unsafe] abstract class IORuntimeCompanionPlatform { this: IORuntime.type
       reportFailure: Throwable => Unit = _.printStackTrace(),
       blockedThreadDetectionEnabled: Boolean = false,
       shutdownTimeout: Duration = 1.second,
-      pollingSystem: PollingSystem = SelectorSystem())
-      : (WorkStealingThreadPool[_], pollingSystem.Api, () => Unit) = {
+      pollingSystem: PollingSystem = SelectorSystem(),
+      uncaughtExceptionHandler: Thread.UncaughtExceptionHandler = (_, ex) =>
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala:83]: Why can't we just use `reportFailure`?

Comment (armanbilge) [reply core/jvm/src/main/scala/cats/effect/unsafe/IORuntimeCompanionPlatform.scala:83]: `reportFailure` is for tasks that fail on the WSTP. `uncaughtExceptionHandler` is for when the WTs _themselves_ fail, which is effectively fatal. Besides, the default `reportFailure` in `IOApp` schedules the printing _on_ the runtime, which is a bad place to send failures _about_ the runtime.

**Review by djspiewak — DISMISSED** [review]

**Review by djspiewak — APPROVED** [review]
