### PR TITLE
Retrieve suspended fiber count directly through the WSTP

### LINKED ISSUE #4405: WorkerThread#getSuspendedFiberCount throws NPE
A few people reported a case when `WorkerThread#getSuspendedFiberCount` throws an NPE. Here, for example, is an issue in the otel4s repo: https://github.com/typelevel/otel4s/issues/973.

The stacktrace:
```
java.lang.NullPointerException: Cannot invoke "cats.effect.unsafe.WeakBag.size()" because "this.fiberBag" is null
 at cats.effect.unsafe.WorkerThread.getSuspendedFiberCount(WorkerThread.scala:1019)
 at cats.effect.unsafe.WorkStealingThreadPool.getSuspendedFiberCount(WorkStealingThreadPool.scala:842)
 at cats.effect.unsafe.metrics.WorkStealingThreadPoolMetrics$$anon$1.suspendedFiberCount(WorkStealingThreadPoolMetrics.scala:265)
```

The `fiberBag` can be unreferenced when the previously blocked thread is removed from the core pool: https://github.com/typelevel/cats-effect/blob/v3.6.1/core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala#L724.

And the [getSuspendedFiberCount](https://github.com/typelevel/cats-effect/blob/v3.6.1/core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala#L1018-L1019) is defined as:
```scala
def getSuspendedFiberCount(): Int =
  fiberBag.size
```

### PR DESCRIPTION
**Pull request by iRevive**
Fixes https://github.com/typelevel/cats-effect/issues/4405.

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala [hunk 1]
```diff
@@ -1015,8 +1015,10 @@ private[effect] final class WorkerThread[P <: AnyRef](
    * @return
    *   the number of asynchronously suspended fibers
    */
-  def getSuspendedFiberCount(): Int =
-    fiberBag.size
+  def getSuspendedFiberCount(): Int = {
+    val bag = fiberBag
+    if (bag ne null) bag.size else 0
+  }
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkerThread.scala]: I suspect that exposing this method was a mistake. If possible, I think we should remove it, and instead fiber bags should be retrieved directly through the WSTP.
https://github.com/typelevel/cats-effect/blob/c7ee9d48f352927523288271524b410828a018ab/core/jvm-native/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala#L96

File: core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala [hunk 2]
```diff
@@ -835,15 +835,8 @@ private[effect] final class WorkStealingThreadPool[P <: AnyRef](
...
-    var sum = 0L
-    var i = 0
-    while (i < threadCount) {
-      sum += workerThreads.get(i).getSuspendedFiberCount().toLong
-      i += 1
-    }
-    sum
-  }
+  private[unsafe] def getSuspendedFiberCount(): Long =
+    fiberBags.map(_.size.toLong).sum
```
Comment (armanbilge) [inline core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala]: Ah, much better! But can we keep the `while` loop implementation? 😅

Comment (iRevive) [reply core/jvm/src/main/scala/cats/effect/unsafe/WorkStealingThreadPool.scala]: Sure

**Review by armanbilge — APPROVED** [review]

**Review by armanbilge — APPROVED** [review]
