### PR TITLE
Propagate Java thread interruption in `Dispatcher#unsafeRunSync`

### LINKED ISSUE #4166: Propagate Java thread interruption in `unsafeRunSync` et al.
We want to handle it similarly to the `TimeoutException`

https://github.com/typelevel/cats-effect/blob/725a4cd25725d23c3aa2213c6a54e9feadb66478/std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala#L58-L65

### PR DESCRIPTION
**Pull request by kamilkloch**
Closes #4166.

### CODE REVIEW

File: std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala [hunk 1]
```diff
@@ -62,6 +62,9 @@ private[std] trait DispatcherPlatform[F[_]] { this: Dispatcher[F] =>
       case t: TimeoutException =>
         cancel()
         throw t
+      case t: InterruptedException =>
+        cancel()
+        throw t
```
Comment (armanbilge) [inline std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala]: Does this syntax work?

```suggestion
      case t: TimeoutException | InterruptedException =>
        cancel()
        throw t
```

File: tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala [hunk 2]
```diff
@@ -42,5 +44,26 @@ class DispatcherJVMSpec extends BaseSpec {
         }
       } yield ok
     }
+
+    "Propagate Java thread interruption in unsafeRunSync" in real {
+      val res = Dispatcher.parallel[IO](await = true).evalMap { dispatcher =>
```
Comment (armanbilge) [inline tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala]:
```suggestion
      val res = Dispatcher.parallel[IO](await = true).use { dispatcher =>
```

File: tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala [hunk 3]
```diff
@@ -42,5 +44,26 @@ class DispatcherJVMSpec extends BaseSpec {
...
+        for {
+          canceled <- Deferred[IO, Unit]
+          io = IO.sleep(1.second).onCancel(canceled.complete(()).void)
+          thread = new Thread(() =>
+            try dispatcher.unsafeRunSync(io)
+            catch { case _: InterruptedException => })
+          _ <- IO(thread.start).as(thread)
+          _ <- IO.sleep(100.millis)
+          _ <- IO(thread.interrupt())
+          _ <- IO(thread.join())
```
Comment (armanbilge) [inline tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala]:
```suggestion
          _ <- IO.blocking(thread.join())
```

File: tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala [hunk 4]
```diff
@@ -42,5 +44,26 @@ class DispatcherJVMSpec extends BaseSpec {
...
+
+    "Propagate Java thread interruption in unsafeRunSync" in real {
+      val res = Dispatcher.parallel[IO](await = true).evalMap { dispatcher =>
+        for {
+          canceled <- Deferred[IO, Unit]
+          io = IO.sleep(1.second).onCancel(canceled.complete(()).void)
+          thread = new Thread(() =>
+            try dispatcher.unsafeRunSync(io)
+            catch { case _: InterruptedException => })
+          _ <- IO(thread.start).as(thread)
```
Comment (armanbilge) [inline tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala]:
```suggestion
          _ <- IO(thread.start)
```

File: tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala [hunk 5]
```diff
@@ -42,5 +44,26 @@ class DispatcherJVMSpec extends BaseSpec {
...
     }
+
+    "Propagate Java thread interruption in unsafeRunSync" in real {
+      val res = Dispatcher.parallel[IO](await = true).evalMap { dispatcher =>
+        for {
+          canceled <- Deferred[IO, Unit]
+          io = IO.sleep(1.second).onCancel(canceled.complete(()).void)
+          thread = new Thread(() =>
+            try dispatcher.unsafeRunSync(io)
+            catch { case _: InterruptedException => })
```
Comment (armanbilge) [inline tests/jvm/src/test/scala/cats/effect/std/DispatcherJVMSpec.scala]: Instead of using `new Thread` what if we wrote this test with `IO.interruptible`?

**Review by armanbilge — COMMENTED** [review]
We should also make a similar change for `IO#unsafeRunSync`.

File: std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala (hunk 1 above)
Comment (kamilkloch) [reply std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala]: Unfortunately, no.

**Comment by kamilkloch** [comment]
> We should also make a similar change for `IO#unsafeRunSync`.

I got a bit lost trying to comprehend the nuanced https://github.com/typelevel/cats-effect/blob/725a4cd25725d23c3aa2213c6a54e9feadb66478/core/jvm/src/main/scala/cats/effect/IOPlatform.scala#L70

File: std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala (hunk 1 above)
Comment (armanbilge) [reply std/jvm/src/main/scala/cats/effect/std/DispatcherPlatform.scala]: It's a bit more sophisticated 😉 thanks for trying.

```suggestion
      case t @ (_: TimeoutException | _: InterruptedException) =>
        cancel()
        throw t
```

**Comment by armanbilge** [comment]
> I got a bit lost trying to comprehend the nuanced

Actually, maybe let's hold off on that change. I forgot that the specification for this method is a bit unusual.

https://github.com/typelevel/cats-effect/blob/725a4cd25725d23c3aa2213c6a54e9feadb66478/core/jvm/src/main/scala/cats/effect/IOPlatform.scala#L45-L48

---

But if we did decide to move forward ...

<details>

You can factor out a package-private version of `unsafeRunAsync` that returns the `Fiber`.

https://github.com/typelevel/cats-effect/blob/725a4cd25725d23c3aa2213c6a54e9feadb66478/core/shared/src/main/scala/cats/effect/IO.scala#L979-L992

Then, you can use that for cancelation in `unsafeRunTimed`.

https://github.com/typelevel/cats-effect/blob/725a4cd25725d23c3aa2213c6a54e9feadb66478/core/jvm/src/main/scala/cats/effect/IOPlatform.scala#L79-L85
</details>

**Comment by kamilkloch** [comment]
> Actually, maybe let's hold off on that change. I forgot that the specification for this method is a bit unusual.

If only you are ok with the resulting discrepancy in sematics between `Dispatcher#unsafeRunSync` and `IO#unsafeRunSync`, I would hold off as well. (Actually, for `unsafeRunTimed` the semantics is already different)

**Review by armanbilge — APPROVED** [review]
thanks!

**Review by djspiewak — APPROVED** [review]
