### PR TITLE
Handle interruption around blocking waits

### LINKED ISSUE #2720: `FatalErrorUnsafeRun` test is now nondeterministic
Rarely failing with this error:

```
[error]   x exit on fatal error with other unsafe runs
[error]    java.lang.InterruptedException
[error]    	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
[error]    	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
[error]    	at cats.effect.IOPlatform.$anonfun$unsafeRunTimed$2(IOPlatform.scala:81)
[error]    	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
[error]    	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:572)
[error]    	at scala.concurrent.package$.blocking(package.scala:124)
[error]    	at cats.effect.IOPlatform.unsafeRunTimed(IOPlatform.scala:81)
[error]    	at cats.effect.IOPlatform.unsafeRunSync(IOPlatform.scala:42)
[error]    	at catseffect.examples.FatalErrorUnsafeRun$.$anonfun$run$3(examplesplatform.scala:42)
[error]    	at cats.effect.unsafe.WorkerThread.blockOn(WorkerThread.scala:607)
[error]    	at scala.concurrent.package$.blocking(package.scala:124)
[error]    	at cats.effect.IOFiber.runLoop(IOFiber.scala:948)
[error]    	at cats.effect.IOFiber.execR(IOFiber.scala:1293)
[error]    	at cats.effect.IOFiber.run(IOFiber.scala:123)
[error]    	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:530) doesn't contain 'Boom!' (IOAppSpec.scala:217)
```

I think this is happening because of the interruption handling on the workers, creating a race condition between the initiating exception and the interruption which results.

### PR DESCRIPTION
**Pull request by vasilmkd**
Resolves #2720.

Removes code that captures mutable variables and volatile at that, for which the Scala runtime has specific classes (`VolatileMutableReference` or something similar, TIL).

### CODE REVIEW

File: core/jvm/src/main/scala/cats/effect/IOApp.scala [hunk 1]
```diff
@@ -261,43 +262,48 @@ trait IOApp {
...
+    val counter = new AtomicInteger(1)
 
     val ioa = run(args.toList)
 
     val fiber =
       ioa.unsafeRunFiber(
         {
-          error = new CancellationException("IOApp main fiber was canceled")
-          latch.countDown()
+          counter.decrementAndGet()
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/IOApp.scala:273]: TIL `decrement` isn't a method on `AtomicInteger.

File: core/jvm/src/main/scala/cats/effect/IOApp.scala [hunk 2]
```diff
@@ -261,43 +262,48 @@ trait IOApp {
...
           if (timeout.isFinite) {
-            cancelLatch.await(timeout.length, timeout.unit)
+            blocking(cancelLatch.await(timeout.length, timeout.unit))
+            ()
           } else {
-            cancelLatch.await()
+            blocking(cancelLatch.await())
           }
+        } catch {
+          case _: InterruptedException =>
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/IOApp.scala]: Won't this happen in Sbt if someone hits Ctrl-C repeatedly? I mean, if the interruption were working *at all* in Sbt, which it isn't.

File: core/jvm/src/main/scala/cats/effect/IOApp.scala [hunk 3]
```diff
@@ -355,6 +361,9 @@ trait IOApp {
         case t: Throwable =>
           t.printStackTrace()
           rt.halt(1)
+        case null =>
+          println(
+            s"result is null but is interrupted? ${Thread.currentThread().isInterrupted()}")
```
Comment (djspiewak) [inline core/jvm/src/main/scala/cats/effect/IOApp.scala]: Debug code? Feels like this case should be handled similarly to the `catch { case _: InterruptedException => ...}` below.

**Review by djspiewak — CHANGES_REQUESTED** [review]
The use of the `Queue` is super nice honestly. I never thought of doing it that way. Some quick comments on the interrupted `poll` cases but otherwise this looks good to me!

File: core/jvm/src/main/scala/cats/effect/IOApp.scala (hunk 2 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/IOApp.scala]: What do you suggest should be done here? No `catch` at all?

File: core/jvm/src/main/scala/cats/effect/IOApp.scala (hunk 3 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/IOApp.scala]: Yes. I had a bug in my original implementation because I accidentally called `queue.poll()` instead of `queue.take()` and I was getting strange `null` results because `poll` is non-blocking and returns `null` if the queue is empty. I forgot to remove this code.

File: core/jvm/src/main/scala/cats/effect/IOApp.scala (hunk 2 above)
Comment (vasilmkd) [reply core/jvm/src/main/scala/cats/effect/IOApp.scala]: I removed it. This matches the previous behavior.

**Review by djspiewak — APPROVED** [review]
