### PR TITLE
Fix memory leak in `Supervisor` internal state

### LINKED ISSUE #4490: Supervisor leaks memory when fibers are canceled quickly
## Reproduction

```scala
//> using scala 3.7.3
//> using dep org.typelevel::cats-effect:3.6.3

import cats.effect.*
import cats.effect.std.Supervisor
import scala.concurrent.duration.*

object SupervisorTest extends IOApp:
  val M = 20
  val N = 100000

  override def run(args: List[String]): IO[ExitCode] =
    for
      _ <- reportMemory
      _ <- Supervisor[IO]
        .use: supervisor =>
          for
            _ <- supervisor
              .supervise(IO.unit)
              .flatMap(_.cancel) // Note: join would be leak free
              .replicateA_(N)
              .parReplicateA_(M)
            _ <- IO.sleep(5.seconds)
            _ <- reportMemory
          yield
            ()
    yield
        ExitCode.Success

  private def reportMemory: IO[Unit] =
    IO.delay:
      val runtime = Runtime.getRuntime()
      runtime.gc()
      val allocatedMemory = runtime.totalMemory() - runtime.freeMemory()
      val allocatedMB = allocatedMemory / (1024 * 1024)
      println(s"Memory taken: $allocatedMB MB")
```

## Output

```
% scala SupervisorTest.scala
Compiling project (Scala 3.7.3, JVM (21))
Compiled project (Scala 3.7.3, JVM (21))
Memory taken: 4 MB
Memory taken: 510 MB
```

That is, after the supervisor has started a bunch a bunch of fibers and _all of them are canceled,_ the memory consumption is 500+ MBs higher than before.

## Notes

If the `_.cancel` is changed to `_.join`, the final memory consumption remains at 4 MB.

You can vary the value of `N` to vary the amount of leaked memory.

This was first suspected in [#4488](https://github.com/typelevel/cats-effect/issues/4488#issuecomment-3289879420), as the implementation of `Supervisor` expects that `.start` guarantees execution of finalizers added with `.guarantee`, `.guaranteeCase`.

### PR DESCRIPTION
**Pull request by durban**
Should fix issue #4490.

Reproducing that issue with the repro in the description there:
```
[info] Memory taken: 6 MB
[info] Memory taken: 520 MB
```

With this PR:
```
[info] Memory taken: 6 MB
[info] Memory taken: 7 MB
```

This issue also adds an (ugly) unittest, which inspects the internal state of the `Supervisor`. We could remove that, if we're satisfied with the fix, but I think it's useful to have it.

~~(Draft, because the test is racy, so I'm waiting for any possible CI failures.)~~

### CODE REVIEW

File: std/shared/src/main/scala/cats/effect/std/Supervisor.scala [hunk 1]
```diff
@@ -141,7 +141,7 @@ object Supervisor {
   def apply[F[_]: Concurrent]: Resource[F, Supervisor[F]] =
     apply[F](false)
 
-  private sealed abstract class State[F[_]] {
+  private[std] sealed abstract class State[F[_]] {
```
Comment (durban) [inline std/shared/src/main/scala/cats/effect/std/Supervisor.scala:144]: Most of the changes in `Supervisor` are just to make it testable (its internal state inspectable).

File: std/shared/src/main/scala/cats/effect/std/Supervisor.scala [hunk 2]
```diff
@@ -169,152 +171,161 @@ object Supervisor {
...
+                    )
                   }
                 }
               }
             }
+          }
 
-            case None => (fa, fin) => F.start(fa.guarantee(fin))
+          case None => { (fa, fin) =>
+            F.start(fa).flatMap { fib => F.start(fib.join.guarantee(fin)).as(fib) }
```
Comment (durban) [inline std/shared/src/main/scala/cats/effect/std/Supervisor.scala:291]: This is the actual fix.

(I believe the other `case` is already correct, because `cancel` joins the underlying fiber.)

**Review by djspiewak — APPROVED** [review]
Wow

It's really unfortunate how racy this is but the fix does look good to me. Excellent job.
